//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PSCAD.rc
//
#define IDR_GRAPHICS_LINE_FORM          4
#define IdApply                         8
#define IdNext                          9
#define IdPrevious                      10
#define IDC_DefnName                    10
#define IDC_CONTROLGROUP_DELETE         10
#define IDC_CONTROLGROUP_DUPLICATE      11
#define IDC_COMBO2                      11
#define IDC_COMBO3                      12
#define IDC_COMBO4                      13
#define IDM_COPY                        15
#define IDM_CUT                         16
#define IDC_DefnDesc                    20
#define IDC_DefnURL                     21
#define IDC_DefnGroup                   22
#define IDM_PASTE                       26
#define IDM_REDO                        29
#define IDM_SELECTALL                   31
#define IDC_GETLICENSE                  34
#define IDC_TABCTRL                     40
#define IDM_UNDO                        43
#define IDM_FIND                        67
#define IDM_MOVE                        88
#define IDD_ABOUTBOX                    100
#define IDC_SETTINGS_EMTDCVER           100
#define IDC_CPanelTitle                 100
#define IDC_PLOTSTEPTIME                100
#define IDC_SETTINGS_TEMPDIR            100
#define IDC_LIBFILES                    100
#define IDC_SETTINGS_WORKDIR            101
#define IDC_SETTINGS_HTMLVIEWER         101
#define IDC_CPanelOptions               101
#define IDS_LF_PROPSHT_CAPTION          101
#define IDC_SETTINGS_HELPDIR            102
#define IDC_SETTINGS_EMTDCFIX           102
#define IDC_SETTINGS_VERSION            103
#define IDC_SETTINGS_EMTDCDIR           103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDC_QUERY_SCOPE                 106
#define IDC_TargetName                  110
#define IDC_CommandLine                 110
#define IDC_PSHeader                    110
#define IDC_SHOW_GRID                   110
#define IDC_BROWSE                      110
#define IDC_TargetDesc                  111
#define IDC_FLOWWIRES                   112
#define IDC_FILE_PATH                   112
#define IDC_TargetDuration              120
#define IDC_PSCommand                   120
#define IDC_SETTINGS_EXTENSIONS         120
#define IDC_TargetTimestep              121
#define IDC_SETTINGS_PROGRAMS           121
#define IDC_TargetPlotstep              122
#define IDC_SETTINGS_EXTENSION          122
#define IDC_SETTINGS_PROGRAM            123
#define IDR_MAINFRAME                   128
#define IDR_PSCADTYPE                   129
#define IDR_PRINTFRAME                  129
#define IDD_POWERFLOW                   129
#define IDC_TargetStartFrom             130
#define IDR_PSCADTYPE1                  130
#define IDD_WORKSPACE_Legacy            131
#define IDD_WORKSPACE_Associations      132
#define IDD_WORKSPACE_Advanced          133
#define IDD_EXIT_BEHAVIOUR              136
#define IDD_WORKSPACE_Runtime           137
#define IDD_WORKSPACE_PowerFlow         138
#define IDD_WORKSPACE_Debug             139
#define IDC_TargetStartSnap             140
#define IDD_POWERFLOW_SOLVED            141
#define IDR_PRINTFRAME1                 145
#define IDD_ABOUTBOX1                   146
#define IDC_TargetOutputFile            147
#define IDC_TargetPlotType              148
#define IDC_TargetSnapType              150
#define IDC_TargetSnapName              151
#define IDC_TargetSnapTime              152
#define IDC_TargetMrunType              161
#define IDC_TargetMrunLength            163
#define IDD_PFQSEARCH_DLG               165
#define IDD_PF_RPT_PROPPAGE1            170
#define IDD_PF_RPT_PROPPAGE2            171
#define IDD_PF_RPT_PROPPAGE3            172
#define IDD_PF_RPT_PROPPAGE4            173
#define IDD_PF_RPT_PROPPAGE5            174
#define IDD_PF_RPT_PROPPAGE6            175
#define IDD_PF_RPT_PROPPAGE7_1          176
#define IDD_PF_RPT_PROPPAGE7_2          177
#define IDD_PF_RPT_PROPPAGE8            178
#define IDD_PF_RPT_PROPPAGE9            179
#define IDC_RunDebug                    191
#define IDC_ECHO_DIMENSIONS             191
#define ID_BROWSE                       200
#define IDC_SETTINGS_BROWSE             200
#define IDC_SOURCEFILES                 200
#define IDC_PP_IDENTIFIERS              201
#define ID_BROWSE_SOURCE                203
#define IDC_B_FROMLIST                  205
#define IDC_B_TOLIST                    206
#define IDC_B_ADD_SEL                   207
#define IDC_B_REMOVE_SEL                208
#define IDC_B_UP                        209
#define IDC_RunAdvanced                 210
#define IDC_HPHeader                    210
#define IDC_RUNTIME                     210
#define IDC_ASSIGN_SEQUENCE             210
#define IDC_NETWORKINTER                210
#define IDC_B_DOWN                      210
#define IDC_B_ADD_ALL                   211
#define IDC_B_REMOVE_ALL                212
#define IDC_STATIC_AVL                  213
#define IDC_STATIC_SEL                  214
#define IDC_TargetLatency               220
#define IDC_HPCommand                   220
#define IDC_LATENCY                     220
#define IDC_A_FROMLIST                  222
#define IDD_PROJECT_Options             223
#define IDD_PROJECT_Network             223
#define IDC_A_TOLIST                    223
#define IDD_PROJECT_BUILD               224
#define IDD_PROJECT_REVISION            225
#define IDC_A_ADD_SEL                   225
#define IDC_A_ADD_ALL                   226
#define IDC_A_REMOVE_SEL                227
#define IDC_A_REMOVE_ALL                228
#define IDC_A_UP                        229
#define IDC_TargetChatter               230
#define IDC_HPPlot                      230
#define IDD_SPLASH                      230
#define IDC_A_DOWN                      230
#define IDC_Z_FROMLIST                  231
#define IDB_SPLASH                      232
#define IDC_Z_ADD_SEL                   232
#define IDC_Z_ADD_ALL                   233
#define IDC_Z_REMOVE_SEL                234
#define IDC_Z_REMOVE_ALL                235
#define IDC_Z_TOLIST                    236
#define IDC_Z_UP                        237
#define IDC_Z_DOWN                      238
#define IDC_PL_AREALIST                 239
#define IDC_TargetBranch                240
#define IDC_HPUseCommand                240
#define IDC_BRANCHTHRESHOLD             240
#define IDC_PL_ZONELIST                 240
#define IDD_USERWIZARD                  241
#define IDC_OB_AREALIST                 241
#define IDD_USERWIZARD_1                242
#define IDC_OB_ZONELIST                 242
#define IDR_CONTROLDATA_TOOLBAR         243
#define IDD_USERWIZARD_2                243
#define IDC_PL_STATIC1                  243
#define IDD_USERWIZARD_3                244
#define IDC_PL_STATIC2                  244
#define IDI_KEYS                        245
#define IDD_USERWIZARD_4                245
#define IDC_OB_STATIC1                  245
#define IDB_WIZARD_2                    246
#define IDC_OB_STATIC2                  246
#define IDB_WIZARD_4                    247
#define IDC_GLOBAL_CHK1                 247
#define IDB_WIZARD_3                    248
#define IDC_GLOBAL_CHK2                 248
#define IDC_GLOBAL_CHK3                 249
#define IDD_PALETTE                     250
#define IDC_GLOBAL_CHK4                 250
#define IDD_LAYERBAR                    251
#define IDC_SAVEAS_EDIT                 251
#define IDB_GFXMODIFY                   252
#define IDC_UPPER_EDIT                  252
#define IDC_SAVEAS_BUTTON               252
#define IDR_GFXFRAME                    253
#define IDC_GLOBAL_CHK5                 253
#define IDB_WIZARD_CMP_LEFT             255
#define IDR_COMPONENTS                  256
#define IDB_WIZARD_CMP_RIGHT            256
#define IDC_OT_AREALIST                 256
#define IDR_COMPONENTS1                 257
#define IDD_STEPDIALOGBAR               257
#define IDC_OT_ZONELIST                 257
#define IDR_COMPONENTS2                 258
#define IDC_OT_STATIC2                  258
#define IDR_COMPONENTS3                 259
#define IDC_OT_STATIC1                  259
#define IDR_GFX_DRAWBAR                 260
#define IDC_LOWER_EDIT                  260
#define IDB_WIZARD_CMP_TOP              261
#define IDC_SET                         261
#define IDB_WIZARD_CMP_BOTTOM           262
#define IDC_V_STATIC                    262
#define IDB_WIZARD_CMP                  263
#define IDC_V_EDIT                      263
#define IDC_V_RADIO1                    264
#define IDR_STEPTOOLBAR                 265
#define IDC_V_RADIO2                    265
#define IDR_CTL_PARAMBAR                266
#define IDC_V_STATIC1                   266
#define IDC_TEXTEDITOR                  267
#define IDC_BUTTON_EDITOR               268
#define IDC_V_SET                       269
#define IDC_V_TOLIST                    270
#define IDD_PROJECT_Mapping             271
#define IDD_PROJECT_Runtime             272
#define IDC_V_REMOVEALL                 272
#define IDC_V_REMOVE                    273
#define IDR_SCRIPTBAR                   274
#define IDC_V_STATIC2                   274
#define IDC_OB1_AREALIST                275
#define IDR_STEPTOOLBAR1                276
#define IDC_OB1_ZONELIST                276
#define IDC_OB1_STATIC1                 277
#define IDC_OB1_STATIC2                 278
#define IDB_BUTTON_IMAGES               279
#define IDD_CASERUNTIME                 280
#define IDD_CASEADVANCED                281
#define IDD_CASEBUILD                   282
#define IDD_PROJECT_Fortran             282
#define IDD_CASEDIAGNOSTICS             283
#define IDD_CASEGENERAL                 284
#define IDD_PROJECT_Library             284
#define IDD_CASEREVISION                285
#define IDD_PROJECT_General             285
#define IDB_WIZARD_FINISH               286
#define IDD_PROJECT_NetEq               286
#define IDB_WIZARD_BOTTOM               287
#define IDB_WIZARD_RIGHT                288
#define IDB_WIZARD_TOP                  289
#define IDB_WIZARD_START                290
#define IDB_WIZARD_LEFT                 291
#define IDB_WIZARD_LAYOUT               292
#define IDB_3DLINE                      293
#define IDB_SPLASH_V400                 296
#define IDC_PREFERENCES_DEFAULT         300
#define IDC_GLOBAL_OPTION               301
#define IDC_NAME_LIST                   302
#define IDC_VALUE                       303
#define IDD_SECURITY                    303
#define IDD_SAVEATQUIT                  304
#define IDR_EDIT                        306
#define IDC_ERRORMESSAGE                310
#define IDC_ERRORDETAILS                311
#define IDR_ROTATIONBAR                 311
#define IDB_OPEN                        319
#define IDC_CopyrightDetails            320
#define IDB_SAVE1                       320
#define ID_RIBBON_HOME_ICONS_SMALL      320
#define IDB_SAVE2                       324
#define IDC_DLGPAGETITLE                330
#define IDC_DLGPAGETITLE2               331
#define IDC_UPDATETOOLS                 333
#define IDB_KEY1                        336
#define IDB_KEY2                        337
#define IDC_DLGCATEGORY                 340
#define IDC_SETTINGS_MENU               340
#define IDD_LICENSE_DETAIL              347
#define IDD_BUS                         348
#define IDC_TargetGenWarnings           350
#define IDD_CUSTOMER_REGISTER           355
#define IDD_PLACEHOLDER                 357
#define IDD_PARAMETER                   358
#define IDD_VIEWER_Properties           358
#define IDD_PROPERTIES_Parameters       358
#define IDD_COMPUTATION                 359
#define IDM_DECOMPOSEWIRE               359
#define IDD_VIEWER_Computations         359
#define IDD_PROPERTIES_Computations     359
#define IDC_TargetGenChecks             360
#define IDR_CTL_LIST                    360
#define IDR_EDIT1                       361
#define IDC_PP_ENABLE                   361
#define IDC_TargetBuildDebug            370
#define IDC_RUNTIME_DEBUG               370
#define IDC_USEMATLAB                   371
#define IDD_TEMPLATE                    372
#define IDD_TEMPLATE_Template           372
#define IDD_TEMPLATE_Module             373
#define IDD_TEMPLATE_Group              374
#define IDD_SIGNALS_Control             375
#define IDD_SIGNALS_Electrical          376
#define IDD_VIEW_CMP                    378
#define IDD_WIREAC_Admittance           380
#define IDD_WIREAC_General              381
#define IDD_WIREAC_Ownership            382
#define IDD_WIREAC_Transmission         383
#define IDD_WIREAC_View                 384
#define IDD_REALTIME_DLG                385
#define IDD_PRINT                       386
#define IDR_GFXFILTERS                  387
#define IDD_MATRIX_VIEWER               388
#define IDD_WIREHVDC_General            390
#define IDD_WIREHVDC_Rectifier          391
#define IDD_WIREHVDC_Inverter           392
#define IDD_WIREXF_General              393
#define IDD_WIREXF_Ownership            394
#define IDD_NEWBRANCH                   395
#define IDD_WIREXF_Misc                 396
#define IDD_MULTIRUN_VIEWER             397
#define IDD_WIREXF_Control              398
#define IDD_WIREXF_Winding1             399
#define IDD_WIREXF_Winding2             400
#define IDD_WIREXF_Winding3             401
#define IDD_PROJECT_Link                404
#define IDD_PROJECT_Dynamics            405
#define IDD_PROJECT_Batch               406
#define IDD_CURVE_VIEWER                407
#define IDB_PF_NODE                     410
#define IDM_GOTODEFINITION              411
#define IDM_SCRIPTMANAGER               412
#define IDD_SCRIPTS                     413
#define IDD_SCRIPTS_Custom              414
#define IDD_LISTCTL_PROPERTY            417
#define IDB_PFQSEARCH                   418
#define IDD_POWERFLOW_Insert            419
#define IDC_BUSOPT                      420
#define IDC_BUS_ALL                     421
#define IDC_BUS_NON                     422
#define IDC_BUS_SEL                     423
#define IDC_BUSMODE                     424
#define IDC_BUSMODE_RADIO1              425
#define IDC_BUSMODE_RADIO2              426
#define IDC_BUSMODE_RADIO3              427
#define IDC_BUSMODE_RADIO4              428
#define IDC_BUSMODE_RADIO5              429
#define IDD_EMTDCWIRE_Model             435
#define IDR_LCP                         435
#define IDD_VIEW_CURVE_PROPERTY         439
#define IDD_UPDATEFILE_DIALOG_FTP       440
#define IDD_MODULE_General              440
#define IDB_VIRTUAL                     441
#define IDD_SPACE_EVENLY                441
#define IDB_LISTCTL                     443
#define IDD_PROPERTIES_Errors           444
#define IDB_WIZARD_FINISH_42            465
#define IDB_WIZARD_TOP_42               467
#define IDB_WIZARD_BOTTOM_42            468
#define IDB_WIZARD_RIGHT_42             472
#define IDB_WIZARD_LAYOUT_42            475
#define IDB_WIZARD_START_42             476
#define IDB_WIZARD_LEFT_42              481
#define IDD_PROPERTIES_Layers           483
#define IDD_PROPERTIES_Ports            484
#define IDD_BRNDATA                     488
#define IDD_POWERFLOW_Page1             489
#define IDD_POWERFLOW_Page2             490
#define IDD_POWERFLOW_Page3             491
#define IDD_POWERFLOW_Page4             492
#define IDR_QUERYBAR                    492
#define IDR_SEARCH                      493
#define IDB_BLUE                        500
#define IDB_STOP                        505
#define IDD_MODULEMAKER_Page1           510
#define IDD_MODULEMAKER_Page2           511
#define IDD_MODULEMAKER_Page3           512
#define IDD_MODULEMAKER_Errors          513
#define IDB_BLUEBOX                     513
#define IDR_CONTROL_SIGNAL_TABLE        514
#define IDR_UNIT_SYSTEM                 515
#define IDR_COMPONENT_TABLE             516
#define IDR_SIGNAL_TABLE                517
#define IDR_PROJECT_MESSAGE_TABLE       518
#define IDR_SCHEMATIC_FORM              519
#define IDR_TLINE_PARAMETERS            520
#define IDR_CABLE_PARAMETERS            521
#define IDR_BUS_PARAMETERS              522
#define IDR_GRAPHICS_SETTINGS_FORM      523
#define IDR_CERTIFICATE_DETAILS_FORM    524
#define IDR_DEFINITION_FORM             525
#define IDR_DEFINITIONLINK_FORM         526
#define IDD_FORTRAN_RENAME              531
#define IDR_USERCMP_ATTRIBUTES_FORM     536
#define IDR_NEWPROJECT                  537
#define IDR_WIRE_ATTRIBUTES_FORM        538
#define IDR_DRAFTCMP_ATTRIBUTES_FORM    539
#define IDR_XML1                        545
#define IDR_DATA_INTEGRITY_CHECKS       545
#define IDR_RIBBON1                     547
#define ID_RIBBON_MAIN_ICONS_SMALL      550
#define ID_RIBBON_MAIN_ICONS_LARGE      554
#define ID_RIBBON_HOME_ICONS_LARGE      556
#define ID_RIBBON_PROJECT_ICONS_LARGE   557
#define ID_RIBBON_PROJECT_ICONS_SMALL   558
#define ID_RIBBON_MAINBUTTON_ICON       559
#define ID_RIBBON_OTHER_ICONS           560
#define ID_RIBBON_VIEW_ICONS_LARGE      561
#define ID_RIBBON_VIEW_ICONS_SMALL      562
#define ID_RIBBON_COMPONENTS_ICONS_LARGE 563
#define ID_RIBBON_COMPONENTS_ICONS_SMALL 564
#define ID_RIBBON_FORMAT_ICONS_LARGE    565
#define ID_RIBBON_FORMAT_ICONS_SMALL    566
#define ID_RIBBON_BETA_ICONS_LARGE      568
#define ID_RIBBON_BETA_ICON_SMALL       569
#define ID_RIBBON_MASTERLIB_LARGE       570
#define ID_RIBBON_MASTERLIB_SMALL       571
#define IDR_HTML1                       573
#define IDR_HTML2                       575
#define IDR_GRID_ENGINE_FORM            579
#define IDR_REMAP_ALL_RESOURCE_LINKS    580
#define IDR_STATIONCANVAS_FORM          581
#define ID_RIBBON_MAPVIEW_ICONS_LARGE   582
#define ID_RIBBON_MAPVIEW_ICONS_SMALL   583
#define ID_RIBBON_BATCH_ICON_SMALL      585
#define ID_RIBBON_BATCH_ICON_LARGE      586
#define ID_RIBBON_POWERFLOW_ICONS_LARGE 587
#define ID_RIBBON_POWERFLOW_ICONS_SMALL 588
#define IDR_GRAPHICS_LABEL_FORM         590
#define IDR_GRAPHICS_BOX_FORM           593
#define IDR_GRAPHICS_PORT_FORM          594
#define IDR_GRAPHICS_ARC_FORM           595
#define IDR_WORKSPACE_SETTINGS_FORM     596
#define IDR_WORKSPACE_ATTRIBUTES_FORM   597
#define IDR_FORTRAN_COMPILERS           603
#define IDR_ROWCANVAS_SETTINGS_FORM     604
#define IDR_EDIT_OUTPUTWND              605
#define ID_RIBBON_DOV_ICONS_SMALL       607
#define ID_RIBBON_DOV_ICONS_LARGE       608
#define IDR_RIBBON_RELEASE              609
#define IDR_COMPARATOR_RESULTS          617
#define IDR_SEARCH_RESULTS_TABLE        618
#define IDR_POWERFLOW_SCHEMAS           619
#define IDR_DC_LINE_FORM                620
#define IDR_FACTS_FORM                  621
#define IDR_HVDC_FORM                   622
#define IDR_LINE_FORM                   623
#define IDR_LOAD_FORM                   624
#define IDR_SHUNT_FORM                  625
#define IDR_XFRM_2W_FORM                626
#define IDR_XFRM_3W_FORM                627
#define IDR_GENERATOR_FORM              628
#define IDR_REFERENCES_TABLE            630
#define IDD_HTMLDIALOG                  631
#define IDR_SIMULATION_FORM             632
#define IDR_SUBSTITUTIONS_TABLE         636
#define IDR_FILEPANE_EDIT               638
#define IDR_SCRIPT_EDIT                 639
#define IDR_MDI_TAB                     640
#define IDM_CLOSE_TAB                   641
#define IDM_CLOSE_OTHER_TABS            642
#define IDR_PROJECT_SETTINGS_FORM       644
#define IDR_PROJECTSETTINGS_GENERAL_CAT 645
#define IDR_PROJECTSETTINGS_RUNTIME_CAT 646
#define IDR_PROJECTSETTINGS_SIMULATION_CAT 647
#define IDR_PROJECTSETTINGS_DYNAMICS_CAT 648
#define IDR_PROJECTSETTINGS_MAPPING_CAT 649
#define IDR_PROJECTSETTINGS_FORTRAN_CAT 650
#define IDR_PROJECTSETTINGS_LINK_CAT    651
#define IDR_GRAPHFRAME_SETTINGS_FORM    655
#define IDR_PLOTFRAME_SETTINGS_FORM     656
#define IDR_OVERLAYGRAPH_SETTINGS_FORM  657
#define IDR_POLYGRAPH_SETTINGS_FORM     658
#define IDR_FILECMP_SETTINGS            659
#define IDR_DIVIDER_SETTINGS            660
#define IDR_STICKY_SETTINGS_FORM        661
#define IDR_CONTROLPANEL_SETTINGS_FORM  662
#define IDR_LCPXAXIS_SETTINGS_FORM      663
#define IDR_BRANCH_TABLE                672
#define ID_MONITOR_FEATURE              673
#define ID_MONITOR_UPDATE_STAT          674
#define IDI_CLOSE                       675
#define IDD_MESSAGE_DIALOG              678
#define IDR_XML2                        690
#define IDR_LAYER_XML                   690
#define IDC_ST                          714
#define IDC_I                           715
#define IDC_J                           716
#define IDM_DIFFERENTIALCOMPONENT_MERGEALLLEFT 717
#define IDM_DIFFERENTIALCOMPONENT_MERGEALLRIGHT 718
#define IDM_DIFFERENTIALCOMPONENT_MERGEINDLEFT_MIN 719
#define IDM_DIFFERENTIALCOMPONENT_MERGEINDLEFT_MAX 738
#define IDM_DIFFERENTIALCOMPONENT_MERGEINDRIGHT_MIN 739
#define IDM_DIFFERENTIALCOMPONENT_MERGEINDRIGHT_MAX 758
#define IDM_COMPARATORGLASSPANE_SETTINGS 759
#define IDM_COMPARATORGLASSPANE_HIDE    760
#define IDM_GLASSPANE_HIDE              761
#define ID_RIBBON_TLINE_ICONS_SMALL     770
#define ID_RIBBON_TLINE_ICONS_LARGE     771
#define IDC_COMBO1                      1001
#define IDC_OUTFILE                     1001
#define IDC_FLYBY_INFO                  1002
#define IDC_FILESTATUS                  1002
#define IDC_SOLVEDFILE                  1002
#define IDC_PROGRESS                    1003
#define IDC_TIMELEFT                    1004
#define IDC_CHECK_SAVE_ENABLED          1005
#define IDC_TRANSFER_RATE               1005
#define IDC_URL                         1006
#define IDC_SOLVE                       1006
#define IDC_SAVE_INTERVAL               1007
#define IDC_NUMFILES                    1008
#define IDC_LICENSE_HOST                1008
#define IDC_EDIT_GRAPH                  1009
#define IDC_PlotTitle                   1010
#define IdEdit_YAxis                    1015
#define IDC_XMIN                        1016
#define IDC_XMAX                        1017
#define IDC_YAxisMin_Default            1017
#define IDC_YAxisMax_Default            1018
#define ID_GRAPH_FOLLOWRUNONOFF         1018
#define IDC_ADJC_PSCM                   1018
#define IDC_OUTPUT                      1019
#define IDC_CategoryExpression          1020
#define IDC_PlotOptions                 1020
#define IDC_FILLFGCOLOR                 1020
#define IDC_COLORBTN_FILLFG             1021
#define IDC_GLIST                       1023
#define IDC_LAYERLIST                   1023
#define IDC_RFontOptions                1024
#define IDC_FILLBKCOLOR                 1025
#define IDC_LineStyleCaption            1025
#define IDC_BUTTONFG                    1027
#define IDC_RMarkerOption               1027
#define IDC_BUTTONBG                    1028
#define IDC_ADJC_SSCM                   1028
#define IDC_COLORBTN                    1029
#define IDC_ADJC_APICM                  1029
#define IDC_COLORBTN_LINE               1030
#define IDC_FILLSTYLE                   1030
#define IDC_ADJC_RTCM                   1030
#define IDC_RLineStyleOption            1031
#define IDC_ADJC_VLCM                   1031
#define IDC_COLORBTN_FILLBG             1032
#define IDC_CurveMention                1032
#define IDC_RColorOption                1033
#define IDC_LINEWEIGHTBUTTON            1034
#define IDC_EDIT2                       1034
#define IDC_MarkersNum                  1036
#define IDC_LineThickness               1037
#define IDC_CONTROLGROUP_NAME           1037
#define IDC_LINEWEIGHT                  1040
#define IDC_CURRENTVALUE                1045
#define IDC_MAX                         1046
#define IDC_MIN                         1049
#define IDC_LINESTYLE                   1050
#define IDC_LINECOLOR                   1060
#define IDC_FONTCOLOR                   1061
#define IDC_SETTINGS_ADVANCED           1067
#define IDC_NEWGROUP_NAME               1070
#define IDC_TEXT                        1070
#define IDC_SECURE_TEXT2                1071
#define IDC_SETTINGS_MASTERLIB          1072
#define IDC_SETTINGS_EMTDCDYN           1074
#define IDC_LIBPATH_EDIT                1074
#define IDC_SETTINGS_EMTDCDF6           1075
#define IDC_LIB_BUTTON                  1077
#define IDC_WIZARD_TITLE                1077
#define IDC_LIBPATH_BUTTON              1078
#define IDC_SFIXLIB_BUTTON1             1078
#define IDC_PICTURE                     1078
#define IDC_SDYNLIB_BUTTON              1079
#define IDC_PAGEFRAME                   1079
#define IDC_SDF6LIB_BUTTON3             1080
#define IDC_PREVIEW                     1080
#define IDC_STEPEDIT                    1080
#define IDC_PREVIEW2                    1081
#define IDC_EMTDCDIR_BUTTON             1081
#define IDC_PREVIEW3                    1082
#define IDC_CHECK_LICENSE_TYPE          1087
#define IDC_PROJECT_ONDEMAND            1087
#define IDC_FILLBACKGROUND              1087
#define IDC_UPDATECASES                 1087
#define IDC_CHECK_VERSION_TYPE          1088
#define IDC_CHECK_EXPIRE_TIME           1089
#define IDC_CHECK_EXPIRATION            1089
#define IDC_CHECK_LICENSE               1090
#define IDC_DISPLAYNAME                 1090
#define IDC_NOSTORAGE                   1090
#define IDC_SIGNAL_STORE                1090
#define IDC_INVERT                      1090
#define IDC_PROCESS_ENVIRONMENT_VARIABLES 1090
#define IDC_INTERNAL                    1090
#define IDC_SEQUENCENUM                 1091
#define IDC_DISPLAYVOLTAGE              1091
#define IDC_SIGNAL_FLOW                 1091
#define IDC_FILE_CHECKBOX               1091
#define IDC_ENABLE_GDIPLUS              1091
#define IDC_MERGE_BUSES                 1092
#define IDC_ENABLE_ANTIALIAS            1092
#define IDC_UNIT_CONVERT                1093
#define IDC_ANTIALIASINGMODE            1094
#define IDC_SAVEMESSAGES2               1095
#define IDC_ELECTRICAL_TYPE             1097
#define IDC_ADVANCED_ACQUIRERELEASE     1100
#define IDC_RADIO_METRICS               1101
#define IDC_ADVANCED_DETAILS            1102
#define IDC_EDIT_METRICS                1102
#define IDC_ADVANCED_SUMMARY            1103
#define IDC_BTN_METRICS                 1103
#define IDC_RADIO_LICENSE               1104
#define IDC_METRICS_BROWSE              1104
#define IDC_EDIT_LISENCE                1105
#define IDC_EDIT_TRIAL                  1105
#define IDC_BTN_TRIAL                   1106
#define IDC_STATIC_LICENSE_TYPE         1107
#define IDC_STATIC_VERSION_TYPE         1108
#define IDC_EDIT_LICENSE                1109
#define IDC_HAxisText                   1110
#define IDC_NodeName                    1110
#define IDC_DEFN_NAME                   1110
#define IDC_BTN_ENTER_LICENSE           1110
#define IDC_BTN_LICENSE                 1110
#define IDC_TRIAL_BROWSE                1111
#define IDC_TINYLEVEL                   1112
#define IDC_LICENSE_BROWSE              1112
#define IDC_SECURITY_ADVANCED           1115
#define IDC_SECURITY_EDIT               1116
#define IDC_SECURITY_RETRY              1117
#define IDC_SECURITY_DEFAULT_BOX        1118
#define IDC_SECURITY_NOTE               1119
#define IDC_HAxisMax                    1120
#define IDC_DEFN_TITLE1                 1120
#define IDC_STATIC_EXPIRE_TIME          1120
#define IDC_STATIC_EXPIRATION           1120
#define IDC_DEFN_TITLE2                 1121
#define IDC_DEFN_TITLE3                 1122
#define IDC_SAVEATQUIT_NO               1122
#define IDC_HAxisMax_Default            1123
#define IDC_NEW_NAME                    1123
#define IDC_SRC_BUTTON                  1124
#define IDC_BUTTON_DETAIL               1127
#define IDC_LICENSE_DETAIL              1127
#define IDC_BUTTON_COPY                 1128
#define IDC_MLABVER_COMBO               1129
#define IDC_HAxisMin                    1130
#define IDC_VISIBILITY                  1130
#define IDC_PORT_TOP                    1130
#define IDC_MLABPATH_BUTTON             1130
#define IDC_PORT_LEFT                   1131
#define IDC_PORT_RIGHT                  1132
#define IDC_LICENSE_INFO                1132
#define IDC_PORT_BOTTOM                 1133
#define IDC_HAxisMin_Default            1134
#define IDC_SOLUTION                    1134
#define IDC_MATRIX_ORDER                1134
#define IDC_MLABPATH_EDIT               1135
#define IDC_LICENSE_ACTIVE              1137
#define IDC_EDIT1                       1138
#define IDC_EDIT_COMPANY_NAME           1138
#define IDC_LF_RUNTIME_STATIC           1138
#define IDC_YAXIS                       1138
#define IDC_WIZARD_DESCRIPTION          1138
#define IDC_BASE_FREQUENCY              1138
#define IDC_VIEWSTYLE                   1139
#define IDC_PORTNUMBER                  1139
#define IDC_HAxisGrid                   1140
#define IDC_DEFN_MODULE                 1140
#define IDC_SYNTAXCOLORING              1140
#define IDC_LINENUMBERS                 1141
#define IDC_LICENSE_AVAIABLE            1142
#define IDC_EDIT_ADDRESS                1142
#define IDC_ACTIVE_LICENSE              1143
#define IDC_EDIT_ADDRESS2               1143
#define IDC_EDIT_ADDRESS3               1144
#define IDC_FORTRANSTYLE                1144
#define IDC_EDIT_CITY                   1145
#define IDC_EDIT_PROVINCE               1146
#define IDC_EDIT_POSTAL                 1147
#define IDC_EDIT_COUNTRY                1148
#define IDC_PROJECT                     1149
#define IDC_EDIT_PHONE                  1149
#define IDC_HAxisFormat                 1150
#define IDC_EDIT_EMAIL                  1150
#define IDC_BUTTON_RESET                1151
#define IDC_COPYINFO                    1152
#define IDC_STATIC_REGISTER             1152
#define IDC_EDIT_USER_NAME              1153
#define IDC_EDIT_FAX                    1154
#define IDC_GENDER                      1155
#define IDC_RADIO2                      1156
#define IDC_EMAIL_ID                    1157
#define IDC_LIST2                       1159
#define IDC_BTN_HOST_CHANGE             1159
#define IDC_HAxisPrecision              1160
#define IDC_LICENSE_ACTIVATE            1160
#define IDC_FLATSTART                   1163
#define IDC_CHANGEDATA                  1165
#define IDC_BUTTON_SAVE_AS              1166
#define IDC_AREAVOLTAGE                 1167
#define IDC_ZEROTRIGGER                 1167
#define IDC_TEMPLATE                    1168
#define IDC_PROCESSCOMM                 1169
#define IDC_HAxisOptions                1170
#define IDC_PROCESSCOMM2                1170
#define IDM_POINT_TO                    1180
#define IDC_MATRIX_SPLIT                1185
#define IDC_MATRIX_SWITCH               1186
#define IDC_SHOW_SEQUENCE               1188
#define IDC_FILE_PERSIST                1189
#define IDC_FILE_DESC                   1190
#define IDC_RUN_MANUAL                  1191
#define IDC_PROJECT_NAME                1191
#define IDC_ECHO_PARAMETERS             1192
#define IDC_RUN_ANIMATE                 1192
#define IDC_FILE_DESC2                  1192
#define IDC_FILE_LABELS                 1192
#define IDC_ECHO_DATA                   1193
#define IDC_RUNTIMEMEASUREMENT          1194
#define IDC_RUNTIME_CHART               1202
#define IDC_DETAILS                     1204
#define IDC_DEFAULT_BOX                 1205
#define IDC_SUBSYSTEM                   1206
#define IDC_MAPPING_INFO                1209
#define IDC_CmpWiz_ConnectTitle         1210
#define IDC_SHOW_VIRTUALS               1210
#define IDC_SHOW_MARGINS                1211
#define IDC_MAP_BEFORE                  1212
#define IDC_PFQLIST                     1212
#define IDC_LABEL1                      1213
#define IDC_LABEL2                      1214
#define ID_CLEAR                        1216
#define ID_DISPLAY                      1217
#define IDC_PFQTREE                     1218
#define IDC_CmpWiz_Connection           1220
#define IDC_PORT_TEXT                   1221
#define IDC_NORMAL                      1222
#define IDC_SWITCHED                    1223
#define IDC_BRANCH_FILL                 1224
#define IDC_MATRIX_BRANCH               1225
#define IDC_MAP_AFTER                   1227
#define IDC_ETYPE                       1230
#define IDC_XAXIS                       1237
#define IDC_NOTES                       1239
#define IDC_GraphTitle                  1240
#define IDC_SIGNAL_TYPE                 1240
#define IDC_ALL                         1240
#define IDC_SELECTED                    1244
#define IDC_LCP                         1245
#define IDC_SIMPLE                      1247
#define IDC_BORDER                      1248
#define IDC_SUNKEN                      1249
#define IDC_GraphOptions                1250
#define IDC_PORT_NAME                   1250
#define IDC_FRAME                       1250
#define IDC_MULTIRUN_VIEWER             1250
#define IDC_TOOL_LIST                   1252
#define IDC_LIBRARY_LIST                1253
#define IDC_CASE_LIST                   1254
#define IDC_PORT_LABEL                  1260
#define IDC_UPDATE_LIST                 1261
#define IDC_LIST1                       1267
#define IDC_CmpWiz_IsArray              1270
#define IDC_DETECTCHATTER               1273
#define IDC_PORT_TYPE                   1273
#define IDC_INPUT_TYPE                  1273
#define IDC_SUPRESSCHATTER              1274
#define IDC_RADIO3                      1274
#define IDC_NETWORKIDEAL                1275
#define IDC_STATIC_SS                   1276
#define IDC_PAGEHEADER                  1278
#define IDC_PAGEFOOTER                  1279
#define IDC_PORT_DIM                    1280
#define IDC_PAGEBORDER                  1280
#define ID_USER_SEARCH                  1285
#define IDC_PARAMETER                   1286
#define IDC_SECURITY_LOG                1287
#define IDC_FILE_NAME                   1296
#define IDC_RETURN_CERTIFICATE          1298
#define IDC_RETAIN_CERTIFICATE          1299
#define IDC_EXPLANATION                 1300
#define IDC_DONTASKAGAIN                1301
#define IDC_SECURE_TEXT                 1305
#define IDC_SECURE_TEXT1                1305
#define ID_BROWSE_LIB                   1309
#define IDC_CmpWiz_PageSize             1310
#define IDC_VAxisText                   1310
#define IDC_PAPER_SIZE                  1310
#define IDC_PAGE_SIZE                   1310
#define IDC_STATIC_TEXT                 1310
#define IDC_ADVANCED_ACTIVATE           1312
#define IDC_ADVANCED_ACTIVATE_TEXT      1313
#define IDC_ADVANCED_EDITPSWD           1314
#define IDC_ADVANCED_VIEWLOG            1315
#define IDC_BUTTON2                     1315
#define IDC_ADVANCED_TESTCONTACT        1316
#define IDC_ADVANCED_EDITPSWD2          1316
#define IDC_HOSTNAME                    1318
#define IDC_HOSTNAME2                   1319
#define IDC_ACLINENAME                  1319
#define IDC_VAxisMin                    1320
#define IDC_ORIENTATION                 1320
#define IDC_VAxisMax                    1330
#define IDC_VAxisGrid                   1340
#define IDC_VAxisFormat                 1350
#define IDC_VAxisPrecision              1360
#define IDC_VAxisOptions                1370
#define IDC_STATIC1                     1381
#define IDC_STATIC2                     1382
#define IDC_STATIC3                     1383
#define IDC_STATIC4                     1384
#define IDC_STATIC5                     1385
#define IDC_STATIC6                     1386
#define IDC_STATIC7                     1387
#define IDC_STATIC8                     1388
#define IDC_CurveList                   1410
#define IDC_CurveRaise                  1420
#define IDC_CurveLower                  1430
#define IDC_CurveText                   1440
#define IDC_CurveStyle                  1450
#define IDC_CurvePattern                1460
#define IDC_CurveMarker                 1470
#define IDC_CurveColour                 1480
#define IDC_CurveOptions                1490
#define IDM_OPEN                        2000
#define IDM_NEW                         2001
#define IDC_NAME                        2010
#define IDC_DIMENSION                   2050
#define IDC_ParamDim                    2100
#define IDM_REPLACE                     2121
#define IDM_REFRESH                     2300
#define IDC_ArcColor                    3010
#define IDC_LabelText                   3010
#define IDC_ArcStyle                    3020
#define IDC_ArcWeight                   3030
#define IDC_LabelSize                   3030
#define IDC_ArcStart                    3040
#define IDC_LabelStyle                  3040
#define IDC_ArcSweep                    3050
#define IDC_LabelCond                   3050
#define IDC_ArcNode                     3060
#define IDC_ArcCond                     3070
#define IDC_PageDisplay                 3070
#define IDC_PagePaperSize               3071
#define IDC_PageOrientation             3072
#define IDC_EMTDC_BATCH_ENAB            3073
#define IDC_BATCH_SUBSTIT_CTRL          3074
#define IDM_PAGEBACK                    5000
#define IDM_GROUPNAME_EDIT              5001
#define IDM_NEWCURVE                    5002
#define IDM_NEWREPORT                   5003
#define IDM_ASS_Delete                  5004
#define IDM_PROJECTADD                  5005
#define IDM_SOLVECONSTANTS              5007
#define IDM_SHOWNUMBER                  5010
#define IDM_SHOWVOLTAGE                 5011
#define IDM_OFFSETRSIDE                 5012
#define IDM_OFFSETLSIDE                 5013
#define IDM_OFFSETCENTER                5014
#define IDM_OFFSETRIGHT                 5015
#define IDM_OFFSETLEFT                  5016
#define IDM_EXPORT                      5018
#define ID_WMODE                        5019
#define IDM_GRAPH_ZOOMONOFF             5020
#define IDM_GRAPH_ZOOMUNDO              5021
#define IDM_GRAPH_CROSSHAIRS_ONOFF      5022
#define IDM_GRAPH_CROSSHAIRS_TRACENEXTCURVE 5023
#define IDM_GRAPH_CROSSHAIRS_TRACEPREVCURVE 5024
#define IDM_GRAPH_CROSSHAIRSCURVE_ONOFF 5025
#define IDM_GRAPH_CREATE                5026
#define IDM_GRAPH_AUTORANGEX            5027
#define IDM_GRAPH_AUTORANGEY_ACTUAL     5028
#define IDM_GRAPH_AUTORANGEY            5029
#define IDR_VIEW_ZOOMINTO               5046
#define IDR_VIEW_ZOOMOUTTO              5047
#define IDR_VIEW_ZOOMRECT               5048
#define IDR_VIEW_ZOOMEXTENTS            5049
#define IDM_EDIT_SEARCH                 5051
#define IDM_EDITGRAPHICS                5052
#define IDM_EDIT_PREFERENCES            5053
#define IDM_EDIT_SETTINGS               5054
#define IDM_EDIT_EXPORT_CLIPBOARD       5055
#define IDM_EDIT_EXPORT_FILE            5056
#define IDM_EMTDC_STOP                  5060
#define IDM_EMTDC_PAUSE                 5061
#define IDM_EMTDC_COMPILEALL            5063
#define IDM_EMTDC_MAKE                  5064
#define IDM_EMTDC_STEP                  5065
#define IDM_EMTDC_START                 5066
#define IDM_EMTDC_SNAPSHOT              5067
#define IDM_EMTDC_RECORD                5068
#define IDM_SAVE_PROJECT                5070
#define IDM_SAVE_PROJECT_AS             5071
#define IDM_CREATE_LIBRARY              5073
#define IDM_CREATE_SYSTEM               5074
#define IDM_VIEW_WORKSPACE              5075
#define IDM_VIEW_OUTPUT                 5076
#define IDM_VIEW_GLOBALCONSTS           5077
#define IDM_FORMAT_GLOBALCONSTS         5078
#define IDM_SAVE_AS                     5079
#define IDM_HELP                        5080
#define IDM_HELP_ABOUT_PSCAD            5081
#define IDM_HELP_CONTENTS               5082
#define IDM_HELP_CWS                    5083
#define IDM_HELP_CPANELS                5084
#define IDM_HELP_COPYRIGHT              5085
#define IDM_HELP_TECHSUPPORT            5086
#define IDM_HELP_INDEX                  5087
#define IDM_HELP_KEYBOARD               5088
#define IDM_HELP_TLINES                 5089
#define IDM_HELP_PLOTS                  5090
#define IDM_HELP_WHATSNEW               5091
#define IDM_DEFINITION_MODIFIED         5092
#define IDM_FILE_PRINTER_SETUP          5100
#define IDM_FILE_PRINT                  5101
#define IDM_FILE_EXIT                   5102
#define IDM_FILE_PRINT_PAGE             5103
#define IDM_FILE_PRINT_PREVIEW_PAGE     5104
#define IDM_FILE_PRINT_ALL              5105
#define IDM_FILE_PRINT_PREVIEW_ALL      5106
#define IDM_FILE_PRINT_SELECTION        5107
#define IDM_FILE_PRINT_PREVIEW_SELECTION 5108
#define IDM_PFLOW_RUN                   5120
#define IDM_SYS_SUMMARY                 5125
#define IDM_BUS_POWERFLOW               5126
#define IDM_AREA_SUMMARY                5127
#define IDM_ZONE_SUMMARY                5128
#define IDM_API_SUMMARY                 5129
#define IDM_ZPI_SUMMARY                 5130
#define IDM_ZONE_PLOSS                  5132
#define IDM_ZONE_OVERRATING             5134
#define IDM_AREA_ABNORMALBUSES          5135
#define IDM_ZONE_ABNORMALBUSES          5136
#define IDM_VIEW_MAINBAR                5150
#define IDM_VIEW_DRAFTBAR1              5151
#define IDM_VIEW_DRAFTBAR2              5152
#define IDM_VIEW_DRAFTBAR3              5153
#define IDM_ADDCURVETONEWPLOT           5160
#define IDM_Section_NewEntry            5163
#define IDM_Section_DeleteEntry         5164
#define IDM_GRID                        5165
#define IDM_SAVEGRAPHICS                5167
#define IDM_RELOADGRAPHICS              5168
#define IDM_SAVEDIALOG                  5169
#define IDM_RELOADDIALOG                5170
#define IDM_DELETE_SETTINGS             5171
#define IDM_OPTIONS_SETTINGS            5172
#define IDM_ASS_Add                     5173
#define IDM_ASS_Browse                  5174
#define IDR_VIEW_SPLITV                 5200
#define IDR_VIEW_SPLITH                 5201
#define IDM_VIEW_EXPAND                 5202
#define IDM_VIEW_COLLAPSE               5203
#define IDM_PRINTSELECTION              5205
#define IDM_CREATEINSTANCE              5206
#define IDM_RESET                       5218
#define IDM_UP                          5220
#define IDM_DOWN                        5221
#define IDM_LOAD                        5240
#define IDM_APPLY                       5241
#define IDM_EDIT                        5242
#define IDM_EDITWIRE                    5243
#define IDM_EDITWIREBRANCH              5244
#define IDM_PROPS                       5245
#define IDM_EDITFIELD                   5246
#define IDM_PLOT_SETASINITIAL           5247
#define IDM_PLOT_REVERTTOINITIAL        5248
#define IDM_EDITUSERCMP                 5249
#define IDM_ADDMETER                    5260
#define IDM_ADDCONTROL                  5261
#define IDM_ADDCURVE                    5262
#define IDM_COMPONENT_WIZARD            5263
#define IDM_CASEPROPS                   5270
#define IDM_VIEWMAP                     5271
#define IDM_VIEWMAKE                    5272
#define IDM_VIEWINPUTFILE               5274
#define IDM_VIEWCONSTANTSFILE           5275
#define IDM_VIEWOUTPUTFILE              5277
#define IDM_PAGECOMPILE                 5290
#define IDM_BLACKBOX                    5291
#define IDM_USERVIEWPARAMETERS          5295
#define IDM_USERVIEWVARIABLES           5296
#define IDM_RESTORE                     5300
#define IDM_SET                         5302
#define IDM_NEWSECTION                  5303
#define IDM_PREVIEWEND                  5310
#define IDM_PREVIEWPRINT                5311
#define IDM_PORTRAIT                    5312
#define IDM_LANDSCAPE                   5313
#define IDM_PRINTTOFITON                5314
#define IDM_PRINTTOFITOFF               5315
#define IDM_PREVIEWFIRST                5316
#define IDM_PREVIEWPREV                 5317
#define IDM_PREVIEWNEXT                 5318
#define IDM_PREVIEWLAST                 5319
#define IDR_CMP_MIN                     5400
#define IDR_NEWAMMETER                  5401
#define IDR_NEWANNOTATION               5402
#define IDR_NEWBUS                      5404
#define IDR_NEWCABLEINTERFACE           5405
#define IDR_NEWCAPACITOR                5407
#define IDR_NEWDIAL                     5408
#define IDR_NEWJUNCTION                 5409
#define IDR_NEWIMPORT                   5410
#define IDR_NEWCONTROLPANEL             5411
#define IDR_NEWDLABEL                   5412
#define IDR_NEWDMERGE                   5413
#define IDR_NEWDTAP                     5414
#define IDR_NEWEXPORT                   5415
#define IDR_NEWGROUND                   5417
#define IDR_NEWGRAPHFRAME               5418
#define IDR_NEWINDUCTOR                 5420
#define IDR_NEWINTEGERC                 5421
#define IDR_NEWNLABEL                   5422
#define IDR_NEWMETER                    5423
#define IDR_NEWPGB                      5424
#define IDR_NEWPUSHBUTTON               5425
#define IDR_NEWSOURCE                   5426
#define IDR_NEWREALC                    5427
#define IDR_NEWRESISTOR                 5428
#define IDR_NEWSELECTOR                 5429
#define IDR_NEWSLIDER                   5430
#define IDR_NEWSTICKY                   5431
#define IDR_NEWSWITCH                   5432
#define IDR_NEWTLINEINTERFACE           5434
#define IDR_NEWUNITY                    5435
#define IDR_NEWVOLTMETER                5436
#define IDR_NEWVOLTMETER2GND            5437
#define IDR_NEWXNODE                    5438
#define IDR_NEWWIRE                     5439
#define IDR_NEWBREAKOUT                 5440
#define IDR_NEWPLOTFRAME                5441
#define IDR_NEWGROUNDDATA               5442
#define IDM_NEW_DIAL                    5443
#define IDM_NEW_METER                   5444
#define IDM_NEW_BUTTON                  5445
#define IDM_NEW_SWITCH                  5446
#define IDM_NEW_SELECTOR                5447
#define IDM_NEW_SLIDER                  5448
#define IDR_NEWTICT                     5449
#define IDR_NEWINTERCHANGE              5451
#define IDR_NEWEXCHANGE                 5452
#define IDR_NEWSSI                      5453
#define IDR_NEWARROWA                   5460
#define IDR_NEWARROWC                   5461
#define IDR_NEWARROWS                   5462
#define IDR_NEWPLOTFRAME2               5463
#define IDR_NEWDIVIDER                  5464
#define IDR_NEWRECTANGLE                5465
#define IDR_NEWRADIOLINK                5466
#define IDR_NEWMULTIMETER               5467
#define IDR_NEWOSCILLOSCOPE             5468
#define IDR_MODULEMAKER                 5470
#define IDR_CMP_MAX                     5500
#define IDR_NEWACLINE                   5502
#define IDR_NEWHVDC                     5503
#define IDR_NEWSHUNT                    5504
#define IDR_NEWFIXED_SHUNT              5505
#define IDR_NEWFACTS                    5506
#define IDR_NEWLOAD                     5507
#define IDR_NEWW3XFORMER                5508
#define IDR_NEWW2XFORMER                5509
#define IDR_NEWGENERATOR                5510
#define IDR_NEWLINEOUTDISP              5511
#define IDR_NEWSTUB                     5512
#define IDR_GFX_MIN                     5600
#define IDR_NEWLINE                     5601
#define IDR_NEWRECT                     5602
#define IDR_NEWELLIPSE                  5603
#define IDR_NEWARC                      5604
#define IDR_NEWTEXT                     5605
#define IDR_NEWNODE                     5611
#define IDR_NEWHALFARC                  5612
#define IDM_LAYERFILTERS                5613
#define IDM_SHOWLINES                   5614
#define IDM_SHOWBOXES                   5615
#define IDM_SHOWOVALS                   5616
#define IDM_SHOWARCS                    5617
#define IDM_SHOWLABELS                  5618
#define IDM_SHOWALL                     5619
#define IDM_HIDEALL                     5620
#define IDM_SHOWALLTYPES                5621
#define IDM_HIDEALLTYPES                5622
#define IDM_SHOWNODES                   5624
#define IDM_SHOWIMAGES                  5625
#define IDR_GFX_MAX                     5626
#define IDM_LAYERINDEX                  5627
#define IDR_SETLINECOLOR                5670
#define IDR_SETBGCOLOR                  5671
#define IDR_SETFGCOLOR                  5672
#define IDR_SETFILLSTYLE                5673
#define IDR_SETLINESTYLE                5674
#define IDR_SETLINEWEIGHT               5675
#define IDR_UPDATELINECOLOR             5676
#define IDR_UPDATEFILL                  5677
#define IDR_UPDATELINESTYLE             5680
#define IDR_UPDATELINEWEIGHT            5681
#define IDM_CONTROLSETTINGS             5700
#define IDM_NEWMETER                    5704
#define ID_DRAG                         5706
#define IDM_DOCKTREEVIEW_HIDE           5712
#define IDM_DOCKTREEVIEW_PROPERTIES     5713
#define IDM_VIEW_PANE                   5714
#define IDM_HIDE_PANE                   5715
#define IDW_BLACK                       5720
#define IDW_MAROON                      5721
#define IDW_GREEN                       5722
#define IDW_OLIVE                       5723
#define IDW_NAVY                        5724
#define IDW_PURPLE                      5725
#define IDW_CYAN                        5726
#define IDW_GRAY                        5727
#define IDW_SILVER                      5728
#define IDW_RED                         5729
#define IDW_LIME                        5730
#define IDW_YELLOW                      5731
#define IDW_BLUE                        5732
#define IDW_FUSHIA                      5733
#define IDW_AQUA                        5734
#define IDW_WHITE                       5735
#define IDW_PICKWELL                    5736
#define IDW_GFXTOOLBAR                  5740
#define IDC_STEPCOMBO                   5755
#define ID_NEW_TEXTAREA                 5760
#define IDM_VIEW_STEPBAR                5776
#define IDM_EDITDEFINITION              5777
#define ID_SWITCHFRAME                  5778
#define IDM_COPY_TO_CLIPBOARD           5779
#define IDM_SETSEQUENCE                 5781
#define IDC_ENTRYCOMBO                  5782
#define ID_BTN_SPACER                   5783
#define IDR_PAGEBACK                    5793
#define IDR_PREVIEWGFXDIALOG            5794
#define IDR_SHOWUSERCMPLAYERS           5795
#define IDM_PAGELAYOUT                  5796
#define IDM_COMPSTYLE_PLAIN             5797
#define IDM_COMPSTYLE_3D                5798
#define IDM_COMPSTYLE_METAL             5799
#define IDM_FILE_CLOSEWORKSPACE         5800
#define IDM_ADDCURVETONEWANALOG         5802
#define IDM_ADDCURVETONEWDIGITAL        5803
#define IDM_ADDCURVETONEWPOLYGRAPH      5804
#define IDM_ADDCURVETONEWPOLYGRAPHDIGITAL 5805
#define IDR_SETCOLOR                    5815
#define IDM_DEF_PROPS                   5820
#define ID_CTRLTEMP_MENU                5821
#define IDM_SAVETOCURRENTSETTING        5822
#define IDM_SAVEAS_NEWGROUP             5823
#define IDM_DUPLICATEGROUP              5824
#define IDM_RENAMEGROUP                 5825
#define IDM_DELETEGROUP                 5826
#define IDM_VIEW_ROTATEBAR              5828
#define ID_BUTTON5832                   5832
#define IDM_MODULE_SETTINGS             5836
#define IDM_SETTINGS                    5838
#define IDM_EIXTEDITOR                  5839
#define IDM_FILTERSMENU                 5847
#define IDM_LARGERPAGE                  5847
#define IDM_SMALLERPAGE                 5848
#define IDM_SAVEAS_NEWSET               5851
#define IDM_HELP_KEYBOARDSHORTCUTS      5853
#define IDM_HELP_COMPONENTWIZARD        5854
#define IDM_HELP_PLOTTING               5855
#define IDM_HELP_CONTROLS               5856
#define IDM_HELP_TLINECABLE             5857
#define IDM_HELP_SUPPORTSERVICES        5858
#define IDM_HELP_WHATNEW                5859
#define IDM_NEWCONTROL                  5860
#define IDR_SETFILLPATTERN              5862
#define ID_DEBUGPAGE                    5865
#define IDM_RUNSCROLLTEST               5876
#define IDM_CLOSE                       5878
#define IDM_VIEW_CONTROL                5881
#define IDM_VIEW_ALL                    5882
#define IDM_VIEW_CONTROLPANEL           5883
#define IDM_VIEW_TLINE                  5884
#define IDM_VIEW_CABLE                  5885
#define IDM_VIEW_IMPORTEXPORT           5886
#define IDM_VIEW_PGB                    5887
#define IDM_VIEW_NODELABEL              5888
#define IDM_VIEW_DATALABEL              5889
#define IDM_VIEW_XNODE                  5890
#define IDM_SORTBY_NAME                 5892
#define IDM_UPDATE                      5893
#define IDM_SORTBY_LOCATION             5894
#define IDM_EMPTY_WORKDIR               5896
#define IDM_CLOSEALL                    5897
#define IDM_VIEW_GRAPH                  5900
#define IDM_VIEW_XYPLOT                 5901
#define IDM_SORTBY_CMPTYPE              5902
#define IDM_SORTBYNAME                  5903
#define IDM_SORTBYDESCRIPTION           5904
#define IDM_BASE_LAYER                  5905
#define ID_DWMODE                       5906
#define IDM_ADDPOLYMETER                5906
#define IDM_SPLIT                       5907
#define IDM_INSERTVERTEX                5907
#define IDM_CONVERTTOWIRE               5913
#define IDM_VIEW_RECORDER               5919
#define IDM_VIEW_DISPLAYDEVICE          5920
#define IDM_VIEW_NAMEDSIGNAL            5921
#define IDM_SORTBY_FNAME                5924
#define IDM_SORTBY_MNAME                5925
#define IDM_VIEW_MODULE                 5931
#define IDM_VIEW_GROUP                  5932
#define IDM_SORTBY_TEXT                 5933
#define IDM_SORTBY_CNAME                5934
#define IDM_VIEW_ALL_CTRLTEMPS          5935
#define IDM_EDITCONFIG                  5945
#define IDM_VIEW_RADIOLINK              5946
#define IDM_SYNC_DEFAULT                5969
#define IDM_POINT_TO_CHANNEL            5972
#define IDM_POINT_TO_INSTANCE           5973
#define IDM_REVERSEWIRE                 5973
#define IDM_INVERTWIRE                  5973
#define ID_SELECTION_JOINWIRES          5975
#define ID_SELECTION_WIREJOINING_SPLITWIRES 5976
#define ID_SELECTION_FORKWIRES          5976
#define IDM_SHOWFRAME                   5977
#define IDM_RELOAD                      5980
#define IDM_RESETALL                    5981
#define IDM_NEW_MODULE_DEFN             5983
#define IDM_SIGNAL_VIEWER               5987
#define IDM_COMPONENT_TABLE             5989
#define ID_RIBBON_VIEW_TOOLBAR_USERPARAMETERGRID 5990
#define IDM_PFLOW_REPORTWRITER          5991
#define IDM_BRANCH_TABLE                5992
#define IDM_SEQUENCE                    5996
#define IDM_SIGNAL_LOCATION             5997
#define IDM_MATRIX                      5998
#define IDM_NEWBRANCH                   5999
#define IDM_CURVE                       6000
#define IDM_MOVETO                      6001
#define IDM_COLLAPSECLUSTER             6002
#define IDM_EXPANDCLUSTER               6003
#define IDM_POWERFLOWROWSELECTED        6004
#define IDM_INSERTCLUSTER               6010
#define IDM_QUICKPF                     6011
#define IDM_PLACECLUSTER                6012
#define IDM_AUTOSENSE                   6014
#define IDM_INSERTMARKED                6015
#define IDM_SORTBY_ID                   6015
#define ID_NAVIGATE_FROM_TABLE_BY_GCHANDLE 6016
#define IDM_SEQ_IMPORT                  6022
#define IDM_RAW_IMPORT                  6023
#define IDM_ADDPHASORMETER              6024
#define IDM_ARROW_TONORTH               6025
#define IDM_REMOVEALLARROWS             6026
#define IDM_ARROW_TOSOUTH               6027
#define IDM_ARROW_TOWEST                6028
#define IDM_ARROW_TOEAST                6029
#define IDM_ARROW_TONORTHWEST           6030
#define IDM_ARROW_TONORTHEAST           6031
#define IDM_ARROW_TOSOUTHWEST           6032
#define IDM_ARROW_TOSOUTHEAST           6033
#define IDM_UPDATE_FILES                6034
#define IDR_VIEW_CURVE                  6036
#define IDR_VIEW_SETTING                6037
#define IDR_VIEW_ALL                    6038
#define IDM_VIEW_FILTERBAR              6039
#define IDM_HELP_SUPPORT_REQUEST        6040
#define IDC_LCPCOMBO                    6042
#define IDR_LCP_HELP                    6043
#define IDM_UNLOAD_PROJECT              6044
#define IDM_HELP_UNITSYSTEM             6046
#define IDM_MAKLIB                      6047
#define IDM_BASELAYER                   6049
#define IDM_INCREASE_ONE_CYCLE          6052
#define IDM_DECREASE_ONE_CYCLE          6053
#define IDR_SAVEMACRO                   6055
#define IDM_ADDOSCILLOSCOPE             6056
#define ID_BUS_VRMS                     6057
#define IDM_APPLYDEFAULT                6060
#define ID_BUS_NETWORKSTUDY             6060
#define IDM_EMTDC_COMPILE               6062
#define ID_INSERTCLUSTER                6063
#define ID_SELECTION_NETWORKSTUDY       6064
#define IDM_NETWORKSTUDY_ADDSELECTION   6065
#define IDM_NETWORKSTUDY_REMOVESELECTION 6066
#define IDM_NETWORKSTUDY_REMOVEALL      6067
#define IDM_NETWORKSTUDY_ADDBUS         6068
#define IDM_NETWORKSTUDY_REMOVEBUS      6069
#define IDM_NETWORKSTUDY_SHOWSCOPE      6070
#define IDC_CTRLTEMP_COMBO              6071
#define IDM_PERSERVE_ACTIVE_CTRLTEMP_AS 6073
#define IDM_DELETE_ACTIVE_CTRLTEMP      6074
#define IDM_ENCRYPT_DEFN                6075
#define IDM_SAVEDATABASE                6076
#define IDM_DECRYPT_DEFN                6076
#define IDM_LOADDATABASE                6077
#define IDM_NETEQ_GENERATE              6078
#define IDM_NETEQ_IMPORT                6079
#define IDM_NAVIGATE_TO                 6093
#define IDM_PASTE_DEFN                  6096
#define IDM_SORT_DEFNS_BYNAME           6097
#define IDM_SORT_DEFNS_BYDESCRIPTION    6098
#define IDR_QUERY_COMBO                 6103
#define IDM_VIEW_QUERYBAR               6104
#define ID_TEST_STARTSERVER             6110
#define ID_TEST_STARTCLIENT             6111
#define IDM_LINENUMBERS                 6118
#define IDM_SYNTAXCOLORING              6126
#define IDM_FORTRANSTYLE                6127
#define IDM_ADD_TO_ALL_SCENARIOS        6132
#define ID_DEFINITION_ENCRYPT           6133
#define ID_DEFINITION_DECRYPT           6134
#define ID_DEFINITION_VIEW              6135
#define IDM_CREATE_CABLE                6138
#define IDM_CREATE_TLINE                6139
#define IDM_CREATE_MODULE               6140
#define IDM_CREATE_COMPONENT            6141
#define ID_USERCMP_APPLYDEFAULTVALUE    6145
#define IDM_PASTE_CURVE                 6146
#define IDM_HELP_CTRLTEMP               6147
#define IDM_PAGEUP                      6149
#define IDM_PAGEFORWARD                 6150
#define ID_VIEW_ALL                     6152
#define ID_VIEW_CONTROLS                6153
#define ID_VIEW_RECORDERS               6154
#define ID_VIEW_NAMEDSIGNALS            6155
#define ID_VIEW_DISPLAYDEVICES          6156
#define ID_VIEW_TLINESCABLES            6159
#define ID_VIEW_RADIOLINKS              6160
#define IDM_CONTROLSIGNAL_VIEWER        6162
#define ID_FILE_IMPORT                  6163
#define IDM_ELECTRICALSIGNAL_VIEWER     6164
#define ID_INITIALIZE_SYSTEM            6164
#define ID_INITSYSTEM                   6165
#define ID_IMPORT_SYSTEMDATAFIEL        6167
#define ID_EXPORTDATABASETOPSS_SIEMENSPSS 6168
#define ID_EXPORT                       6169
#define IDM_NAVIGATE_UPWARD             6169
#define IDM_NAVIGATE_FORWARD            6170
#define ID_EXPORTDATABASETOPSS_XMLDATAFILE 6170
#define IDM_NAVIGATE_BAKCWARD           6171
#define ID_PROJECTTREE_SYSTEMDATABASE   6171
#define IDM_NAVIGATE_PREVIOUS           6172
#define ID_PROJECTTREE_MHRC             6172
#define IDM_NAVIGATE_NEXT               6173
#define ID_PROJECTTREE_STRI             6173
#define IDM_IMPORTDATABASE              6174
#define ID_GRAPHICS_SETTINGS            6175
#define IDM_EXPORTDATABASE              6175
#define IDM_RAW_EXPORT                  6176
#define ID_SYSTEMDATABASE_VIEW          6177
#define IDM_VIEWDATABASE                6178
#define ID_VIEWACTIVESYSTEMDATA         6180
#define IDM_COPY_TO_FILE                6181
#define IDR_SHOWALLLAYERS               6182
#define IDM_EDIT_GLOBALCONSTS           6183
#define IDM_COPYSPECIAL                 6184
#define ID_SCHEMATICCANVAS_PASTESPECIAL 6185
#define ID_DEFINITION_COPYSPECIAL       6187
#define IDM_EDITMODULELINK              6188
#define IDR_INSERT_SVG                  6189
#define IDM_INSPECTXML                  6190
#define IDM_UNLOAD_ALL_PROJECTS         6191
#define IDM_TRANSLATE_OFFCANVAS_OBJ     6192
#define IDM_EDITATTRIBUTES              6193
#define IDM_COMPAREXML                  6193
#define IDM_COMPAREDEFNXML              6194
#define ID_SELECTION_OMPARE             6195
#define ID_Menu                         6196
#define ID_LINKTO_NONE                  6198
#define ID_FILE_IMPORTPROJECT           6200
#define IDM_USER_HELP                   6201
#define ID_RIBBON                       6206
#define ID_DOCKING_WORKSPACE            6238
#define ID_DOCKING_OUPUT                6239
#define ID_DOCKING_WIZARD               6240
#define ID_DOCKING_QUERY                6241
#define ID_DOCKING_MAPVIEW              6242
#define ID_DOCKING_SEARCH_RESULTS       6339
#define ID_DOCKING_PROPS                6340
#define ID_DOCKING_XML_TREE_RESULTS     6341
#define ID_DOCKING_XMLINSPECTOR         6342
#define ID_DOCKING_MESSAGE              6343
#define ID_DOCKING_DATATABLES           6344
#define ID_DOCKING_QUERYTABLE           6345
#define ID_DOCKING_USERPARAMETERGRIDANE 6346
#define ID_DOCKING_BATCH                6347
#define ID_DOCKING_GRID_CLIENT          6348
#define ID_DOCKING_COMPARATOR           6349
#define ID_DOCKING_OUTPUTDUMP           6350
#define ID_DOCKING_REPORT               6351
#define ID_DOCKING_SUPPORT              6352
#define ID_DOCKING_MAP                  6353
#define ID_DOCKING_MAKE                 6354
#define ID_DOCKING_LOG                  6355
#define ID_DOCKING_STARTPAGE            6356
#define ID_DOCKING_COMPARATORTABLE      6357
#define ID_DOCKING_SUBSTITUTIONS_TABLE  6358
#define ID_DOCKING_LAYERS               6359
#define ID_PROJECTTREE_GRIDENGINESETTINGS 6362
#define IDM_GRIDENGINESETTINGS          6363
#define ID_GRIDENGINESETTINGS_SETTINGS  6364
#define ID_GRIDENGINESETTINGS_START     6365
#define ID_GRIDENGINESTART              6366
#define IDM_GRIDENGINESTART             6367
#define IDM_REMAP_RESOURCE_LINKS        6370
#define IDM_ADD_TO_CURRENT_SCENARIO     6375
#define IDM_REMOVE_FROM_CURRENT_SCENARIO 6376
#define IDM_REMOVE_FROM_ALL_SCENARIOS   6377
#define ID_USERCMP_SCENARIOS            6378
#define ID_SET_UNDO_WAYPOINT_START      6390
#define ID_SET_UNDO_WAYPOINT_END        6391
#define ID_LAYER_SELECT_COMPONENTS      6392
#define ID_LAYER_MERGE                  6393
#define ID_LAYER_SHOW_LIST              6394
#define ID_LAYER_HIGHLIGHT              6395
#define ID_RIBBON_MAIN_WORKSPACE        6400
#define ID_RIBBON_MAIN_WORKSPACE_LOAD   6401
#define ID_RIBBON_OPEN_WORKSPACE        6402
#define ID_PROJECTTREE_SIMULATONMANAGER 6404
#define ID_SIMULATONMANAGER_ADDSIMULATION 6405
#define ID_SIMULATONMANAGER_EDITSIMULATION 6406
#define ID_SIMULATONMANAGER_REMOVESIMULATION 6407
#define ID_SIMULATONMANAGER_REM         6408
#define ID_ADDTOSIMULATION_SIM1         6409
#define ID_REMOVEFROMSIMULATION_SIM2    6410
#define ID_ADDTOSIMULATION_NONE         6412
#define ID_WORKSPACETREEROOT_POWERFLOWSOLUTION 6436
#define IDM_POWERFLOW_SETTINGS          6437
#define IDM_WORKSPACE_SETTINGS          6438
#define ID_RIBBON_COMPATATOR_COMPARE_DEFINITION 6447
#define IDM_VIEWREFERENCES              6451
#define ID_WORKSPACE_CLEAN              6455
#define ID_RIBBON_DOV_DOV_HELP          6458
#define ID_SELECTION_UNGROUP            6461
#define ID_PROJECTS_SAVEALL             6462
#define ID_PROJECTS_CLEANALLTEMPORARYFILDERS 6464
#define ID_PROJECTS_OPEN                6465
#define ID_PROJECTS_NEW                 6466
#define ID_WORKSPACETREEROOT_OPEN       6467
#define ID_WORKSPACETREEROOT_RELOAD     6468
#define ID_WIREBRANCH_NETWORKPARAMETERS 6468
#define ID_PROJECTTREE_RELOAD           6469
#define ID_SIMULATIONLISTTREENODE_RUN   6471
#define ID_RUN_NONE                     6472
#define ID_SIMULATIONLISTTREENODE_RUNALL 6473
#define ID_SIMULATIONLISTTREENODE_      6474
#define ID_SIMULATION_RUNALL            6475
#define ID_TASKTREENODE_SIMULATIONOPTIONS 6477
#define ID_SIMULATIONNODE_OPTIONS       6478
#define IDM_SIMULATIONNODE_OPTIONS      6479
#define IDM_SHOW_IN_FOLDER              6480
#define IDM_DELETE_NETWORK_BUS          6481
#define IDM_DELETE_NETWORK_BRANCH       6482
#define IDM_NOTIFY_0                    6483
#define IDM_NOTIFY_1                    6484
#define IDM_NOTIFY_2                    6485
#define ID_RIBBON_TOOLS_COMPARATOR      6490
#define IDR_RIBBON_TOOLS_COMPARATOR     6491
#define ID_STATIONCANVAS_CLEARWIRECACHE 6492
#define IDM_SUBSTITUTION_ADDED          6500
#define IDM_SUBSTITUTION_CHANGED        6501
#define IDM_SUBSTITUTION_REMOVED        6502
#define IDM_SUBSTITUTION_SET_CHANGED    6503
#define IDM_MARK_SUBSITUTIONS_MODIFIED  6504
#define IDM_IMPORT_SUBSTITUTION_SET     6505
#define IDM_EXPORT_SUBSTITUTION_SET     6506
#define IDD_PSCAD_MESSAGE_BOX           6550
#define IDB_PMB_OK                      6551
#define IDB_PMB_CANCEL                  6552
#define IDB_PMB_YES                     6553
#define IDB_PMB_NO                      6554
#define IDB_PMB_CHECKBOX                6559
#define IDI_PMB_ICON_INFORMATION        6560
#define IDI_PMB_ICON_WARNING            6561
#define IDI_PMB_ICON_ERROR              6562
#define IDI_PMB_ICON_QUESTION           6563
#define IDM_COPYSPECIAL_TRANSFER        6612
#define IDM_PASTE_COPYTRANSFER          6613
#define ID_SCHEMATICCANVAS_PASTE        6613
#define IDM_VIEW_PARAMETERSGRID         6615
#define IDM_USESIGNALNAME               6617
#define ID_RUNBATCHTEST                 7000
#define ID_LICENSING_START              7003
#define ID_LICENSING_ADVANCEDREQUEST    7005
#define ID_LICENSING_ADVANCEDRENEW      7007
#define ID_LICENSING_ADVANCEDRELEASE    7009
#define ID_LICENSING_PROCESSRETURNCODE  7010
#define ID_LICENSING_ADVANCEDTEST       7011
#define ID_SEARCHRESULTS_ADD            7012
#define ID_SEARCHRESULTS_CLEAR          7013
#define ID_SEARCHRESULTS_NAMESPACE_CHANGED 7014
#define ID_SEARCHRESULTS_COMPLETE       7015
#define ID_SEARCHRESULTS_SEARCHTERM_CHANGED 7016
#define ID_COMPARATORDATAGRID_ACTION    7020
#define IDM_DELETE_SUBSTITUTION         7050
#define ID_IMPORT_SUBSTITUTIONS         8000
#define ID_PROGRESSTOOLTIP_PRESHOW      8500
#define ID_PROGRESSTOOLTIP_PREHIDE      8501
#define IDM_PARAMETERS                  9999
#define ID_MENU_UNDO                    10001
#define ID_MENU_REDO                    10002
#define ID_MINIMAP_DOCKINGPANE          10005
#define ID_MINIMAP_WND                  10006
#define ID_MENU_NAVIGATE_UPWARD         10010
#define IDM_INCLUDE_PROJECT_START       10500
#define IDM_INCLUDE_PROJECT_END         10756
#define ID_MINIMAP_REDRAW               32500
#define ID_VIEW_LOOKANDFEEL_PLAIN       32802
#define ID_VIEW_LOOKANDFEEL_3D          32803
#define ID_VIEW_LOOKANDFEEL_METAL       32804
#define ID_IMPORTSYSTEMDATAFROMSIMPOW_OPTPOW 32808
#define ID_IMPORTSYSTEMDATAFROMSIMPOW_DYNPOW 32809
#define ID_IMPORTSYSTEMDATAFROMSIMPOW_OTRES 32810
#define ID_EXPORTSYSTEMDATATOSIMPOW_OPTPOW 32812
#define ID_EXPORTSYSTEMDATATOSIMPOW_DYNPOW 32813
#define ID_EXPORTSYSTEMDATATOSIMPOW_OTRES 32814
#define ID_FILE_SAVESIMPOWPRIVATEDATAASXML 32815
#define ID_SOLVER_RUNSIMPOWPOWERFLOW    32816
#define ID_EXPORT_SIMPOWPROJECT         32829
#define IDM_VIEW_BRINGTOFRONT           32843
#define IDM_VIEW_SENDTOBACK             32844
#define IDM_VIEW_REFRESH                32845
#define ID_STRI_SIMPOWDIALOGTEST        32851
#define ID_STRI_SIMPOWDIALOGXML         32852
#define ID_STRI_SIMPOWDIALOGINPUTDSL    32853
#define IDM_EDITPARAMS                  32855
#define IDM_ADD                         32856
#define IDM_ATTACHCOMPONENTS            32856
#define IDM_RESIZE                      32857
#define IDM_RAISE                       32859
#define IDM_LOWER                       32860
#define ID_STRI_TESTDIALOGCOMMONDATA    32900
#define ID_STRI_TESTDIALOGPRIVATEDATA   32901
#define IDM_CLEAR                       32951
#define IDM_ROTATELEFT                  32955
#define IDM_ROTATERIGHT                 32956
#define IDM_ROTATE180                   32957
#define IDM_MIRROR                      32958
#define IDM_FLIP                        32959
#define IDM_DELETE                      32960
#define ID_OUTPUTDUMPWND_APPENDMESSAGE  32966
#define ID_OUTPUTDUMPWND_SETOUTPUT      32967
#define ID_OUTPUTDUMPWND_REFRESH        32968
#define ID_OUTPUTDUMPWND_UNLOAD         32969
#define IDS_HTTPDOWNLOAD_GENERIC_ERROR  32979
#define IDS_HTTPDOWNLOAD_RESOLVING_NAME 32980
#define IDS_HTTPDOWNLOAD_RESOLVED_NAME  32982
#define IDS_HTTPDOWNLOAD_CONNECTING     32983
#define IDS_HTTPDOWNLOAD_CONNECTED      32984
#define IDS_HTTPDOWNLOAD_REDIRECTING    32985
#define IDS_HTTPDOWNLOAD_FAIL_CONNECT_SERVER 32986
#define IDS_HTTPDOWNLOAD_INVALID_HTTP_RESPONSE 32987
#define IDS_HTTPDOWNLOAD_ERROR_READFILE 32988
#define IDS_HTTPDOWNLOAD_INVALID_SERVER_RESPONSE 32989
#define ID_RIBBON_HOME_EDITING_SELECT_FREEHAND 33021
#define ID_RIBBON_HOME_EDITING_SELECT_POINT 33022
#define ID_RIBBON_HOME_RUN_SLOW         33042
#define ID_RIBBON_HOME_RUN_SLOW_AMOUNT  33043
#define ID_RIBBON_HOME_RUN_SKIP         33044
#define ID_RIBBON_HOME_CLIPBOARD_CUT    33045
#define ID_RIBBON_HOME_CLIPBOARD_COPY   33046
#define ID_RIBBON_HOME_CLIPBOARD_PASTE  33047
#define ID_RIBBON_HOME_CLIBOARD_DELETE  33048
#define ID_RIBBON_HOME_COMPILE_BUILDMODIFIED 33049
#define ID_RIBBON_HOME_COMPILE_BUILD    33050
#define ID_RIBBON_HOME_COMPILE_CLEAN    33051
#define ID_RIBBON_HOME_RUN_RUN          33052
#define ID_RIBBON_HOME_RUN_STOP         33053
#define ID_RIBBON_HOME_RUN_PAUSE        33054
#define ID_RIBBON_HOME_RUN_STEP         33055
#define ID_RIBBON_HOME_RUN_SNAPSHOT     33056
#define ID_RIBBON_HOME_RUN_PLOTSPER     33057
#define ID_RIBBON_HOME_SCENARIO_SAVE    33058
#define ID_RIBBON_HOME_SCENARIO_DELETE  33059
#define ID_RIBBON_HOME_SCENARIO_VIEWALL 33060
#define ID_RIBBON_HOME_SCENARIO_SCENARIOSELECT 33061
#define ID_RIBBON_HOME_NAVIGATION_BACK  33062
#define ID_RIBBON_HOME_NAVIGATION_FORWARD 33063
#define ID_RIBBON_HOME_NAVIGATION_UP    33064
#define ID_RIBBON_HOME_EDITING_SELECT   33065
#define ID_RIBBON_HOME_EDITING_SELECT_ALL 33066
#define ID_RIBBON_HOME_EDITING_PAN      33067
#define ID_RIBBON_HOME_EDITING_SEARCHNODE 33068
#define ID_RIBBON_HOME_EDITING_SEARCH   33069
#define ID_RIBBON_HOME_EDITING_UNDO     33070
#define ID_RIBBON_HOME_EDITING_REDO     33071
#define ID_RIBBON_HOME_ZOOMING_ZOOMIN   33072
#define ID_RIBBON_HOME_ZOOMING_ZOOMOUT  33073
#define ID_RIBBON_HOME_ZOOMING_ZOOMPERCENT 33074
#define ID_RIBBON_HOME_ZOOMING_ZOOMPERCENT_START 33075
#define ID_RIBBON_HOME_ZOOMING_ZOOMPERCENT_25 33075
#define ID_RIBBON_HOME_ZOOMING_ZOOMPERCENT_33 33076
#define ID_RIBBON_HOME_ZOOMING_ZOOMPERCENT_50 33077
#define ID_RIBBON_HOME_ZOOMING_ZOOMPERCENT_75 33078
#define ID_RIBBON_HOME_ZOOMING_ZOOMPERCENT_100 33079
#define ID_RIBBON_HOME_ZOOMING_ZOOMPERCENT_125 33080
#define ID_RIBBON_HOME_ZOOMING_ZOOMPERCENT_150 33081
#define ID_RIBBON_HOME_ZOOMING_ZOOMPERCENT_200 33082
#define ID_RIBBON_HOME_ZOOMING_ZOOMPERCENT_300 33083
#define ID_RIBBON_HOME_ZOOMING_ZOOMPERCENT_400 33084
#define ID_RIBBON_HOME_ZOOMING_ZOOMPERCENT_END 33087
#define ID_RIBBON_HOME_ZOOMING_ZOOMEXTENT 33088
#define ID_RIBBON_HOME_ZOOMING_ZOOMRECTANGLE 33089
#define ID_RIBBON_HOME_COMPILE_BUILD_ALL 33090
#define ID_RIBBON_HOME_COMPILE_BUILDMODIFIED_ALL 33091
#define ID_RIBBON_HOME_COMPILE_CLEAN_ALL 33092
#define ID_RIBBON_HOME_SCENARIO_SAVEAS  33097
#define ID_RIBBON_HOME_RUN_RUNALL       33098
#define ID_RIBBON_PROJECT_GENERAL_NAMESPACE 33100
#define ID_RIBBON_PROJECT_GENERAL_DESCRIPTION 33101
#define ID_RIBBON_PROJECT_GENERAL_FULLPATH 33102
#define ID_RIBBON_PROJECT_GENERAL_GENERAL 33103
#define ID_RIBBON_PROJECT_RUNTIME_DURATIONOFRUN 33104
#define ID_RIBBON_PROJECT_RUNTIME_SOLUTIONTIMESTEP 33105
#define ID_RIBBON_PROJECT_RUNTIME_CHANNELPLOTSTEP 33106
#define ID_RIBBON_PROJECT_RUNTIME_STARTUPMETHOD 33107
#define ID_RIBBON_PROJECT_RUNTIME_SMINPUTFILE 33108
#define ID_RIBBON_PROJECT_RUNTIME_BROWSE 33109
#define ID_RIBBON_PROJECT_RUNTIME_SAVECHANNELS 33110
#define ID_RIBBON_PROJECT_RUNTIME_SCOUTPUTFILE 33111
#define ID_RIBBON_PROJECT_RUNTIME_TIMEDSNAPSHOTS 33112
#define ID_RIBBON_PROJECT_RUNTIME_SNAPSHOTFILE 33113
#define ID_RIBBON_PROJECT_RUNTIME_TSTIME 33114
#define ID_RIBBON_PROJECT_RUNTIME_MULTIPLERUN 33115
#define ID_RIBBON_PROJECT_RUNTIME_NUMOFRUN 33116
#define ID_RIBBON_PROJECT_RUNTIME_RUNTIME 33117
#define ID_RIBBON_PROJECT_OTHER_DYNAMIC 33118
#define ID_RIBBON_PROJECT_OTHER_SIMULATION 33119
#define ID_RIBBON_PROJECT_OTHER_MAPPING 33120
#define ID_RIBBON_PROJECT_OTHER_FORTRAN 33121
#define ID_RIBBON_PROJECT_OTHER_LINK    33122
#define ID_RIBBON_PROJECT_RUNTIME_MULTIRUNCONFIG 33123
#define ID_RIBBON_VIEW_WINDOW_SWITCH    33142
#define ID_RIBBON_VIEW_OVERLAY_BOUNDS   33143
#define ID_RIBBON_VIEW_OVERLAY_BUSMONITORING 33144
#define ID_RIBBON_VIEW_OVERLAY_GRIDS    33145
#define ID_RIBBON_VIEW_OVERLAY_SIGNALS  33146
#define ID_RIBBON_VIEW_OVERLAY_SEQUENCE 33147
#define ID_RIBBON_VIEW_OVERLAY_VIRTUALWIRES 33148
#define ID_RIBBON_VIEW_OVERLAYS_CANVASSETTINGS 33153
#define ID_RIBBON_VIEW_PAGE_REFRESH     33155
#define ID_RIBBON_VIEW_PAGE_SIZE        33156
#define ID_RIBBON_VIEW_PAGE_SIZE_START  33157
#define ID_RIBBON_VIEW_PAGE_SIZE_A4     33157
#define ID_RIBBON_VIEW_PAGE_SIZE_A3     33158
#define ID_RIBBON_VIEW_PAGE_SIZE_A2     33159
#define ID_RIBBON_VIEW_PAGE_SIZE_A1     33160
#define ID_RIBBON_VIEW_PAGE_SIZE_OVERSIZE 33161
#define ID_RIBBON_VIEW_PAGE_SIZE_END    33164
#define ID_RIBBON_VIEW_PAGE_ORIENTATION 33165
#define ID_RIBBON_VIEW_PAGE_ORIENTATION_START 33166
#define ID_RIBBON_VIEW_PAGE_ORIENTATION_PORTRAIT 33166
#define ID_RIBBON_VIEW_PAGE_ORIENTATION_LANDSCAPE 33167
#define ID_RIBBON_VIEW_PAGE_ORIENTATION_END 33169
#define ID_RIBBON_VIEW_TOOLBAR_MINIMAP  33175
#define ID_RIBBON_VIEW_TOOLBAR_WORKSPACE 33180
#define ID_RIBBON_VIEW_TOOLBAR_OUTPUT   33181
#define ID_RIBBON_VIEW_TOOLBAR_PROP     33182
#define ID_RIBBON_VIEW_TOOLBAR_COMPWIZARD 33183
#define ID_RIBBON_VIEW_TOOLBAR_DATAQUERY 33184
#define ID_RIBBON_VIEW_TOOLBAR_MESSAGES 33185
#define ID_RIBBON_VIEW_TOOLBAR_SEARCHRESULTS 33186
#define ID_RIBBON_VIEW_TOOLBAR_SUBSTITUTIONS 33187
#define ID_RIBBON_VIEW_TOOLBAR_BATCH    33188
#define ID_RIBBON_VIEW_TOOLBAR_OUTPUTDUMP 33189
#define ID_RIBBON_VIEW_TOOLBAR_MAPVIEW  33190
#define ID_RIBBON_VIEW_TOOLBAR_GRID     33191
#define ID_RIBBON_VIEW_TOOLBAR_DATATABLE 33192
#define ID_RIBBON_VIEW_TOOLBAR_SUPPORT  33193
#define ID_RIBBON_VIEW_TOOLBAR_MAPFILE  33194
#define ID_RIBBON_VIEW_TOOLBAR_MAKEFILE 33195
#define ID_RIBBON_VIEW_TOOLBAR_COMPARATORRESULTS 33196
#define ID_RIBBON_VIEW_TOOLBAR_STARTPAGE 33197
#define ID_RIBBON_VIEW_TOOLBAR_REPORT   33198
#define ID_RIBBON_VIEW_TOOLBAR_LAYERS   33199
#define ID_RIBBON_COMPONENTS_START      33200
#define ID_RIBBON_COMPONENTS_SIMPLE_WIRE 33200
#define ID_RIBBON_COMPONENTS_SIMPLE_RESISTOR 33201
#define ID_RIBBON_COMPONENTS_SIMPLE_INDUCTOR 33202
#define ID_RIBBON_COMPONENTS_SIMPLE_CAPACITOR 33203
#define ID_RIBBON_COMPONENTS_SIMPLE_GROUND 33204
#define ID_RIBBON_COMPONENTS_SIMPLE_NODELABEL 33205
#define ID_RIBBON_COMPONENTS_SIMPLE_XNODE 33206
#define ID_RIBBON_COMPONENTS_SIMPLE_BREAKOUT 33207
#define ID_RIBBON_COMPONENTS_SIMPLE_PIN 33208
#define ID_RIBBON_COMPONENTS_METERS_AMMETER 33209
#define ID_RIBBON_COMPONENTS_METERS_VOLTMETER 33210
#define ID_RIBBON_COMPONENTS_METERS_VOLTMETERTOGROUND 33211
#define ID_RIBBON_COMPONENTS_METERS_MULTIMETER 33212
#define ID_RIBBON_COMPONENTS_INTERFACE_TLINE 33213
#define ID_RIBBON_COMPONENTS_INTERFACE_CABLE 33214
#define ID_RIBBON_COMPONENTS_DEVICES_OUTPUTCHANNEL 33224
#define ID_RIBBON_COMPONENTS_DEVICES_SLIDER 33225
#define ID_RIBBON_COMPONENTS_DEVICES_SWITCH 33226
#define ID_RIBBON_COMPONENTS_DEVICES_DIAL 33227
#define ID_RIBBON_COMPONENTS_DEVICES_PUSHBUTTON 33228
#define ID_RIBBON_COMPONENTS_DATA_DATATAP 33229
#define ID_RIBBON_COMPONENTS_DATA_DATAMERGE 33230
#define ID_RIBBON_COMPONENTS_DATA_DATALABEL 33231
#define ID_RIBBON_COMPONENTS_DATA_INTEGER 33232
#define ID_RIBBON_COMPONENTS_DATA_REAL  33233
#define ID_RIBBON_COMPONENTS_DATA_IMPORT 33234
#define ID_RIBBON_COMPONENTS_DATA_EXPORT 33235
#define ID_RIBBON_COMPONENTS_DATA_RADIOLINK 33236
#define ID_RIBBON_COMPONENTS_GRAPHS_GRAPHPANE 33237
#define ID_RIBBON_COMPONENTS_GRAPHS_XYPLOT 33238
#define ID_RIBBON_COMPONENTS_GRAPHS_CONTROLPANE 33239
#define ID_RIBBON_COMPONENTS_COMMENTS_ANNOTATION 33240
#define ID_RIBBON_COMPONENTS_COMMENTS_STICKYNOTES 33241
#define ID_RIBBON_COMPONENTS_COMMENTS_DIVIDER 33242
#define ID_RIBBON_COMPONENTS_END        33254
#define ID_RIBBON_COMPONENTS_NEWCOMPONENT_NEWCOMPONENT 33255
#define ID_RIBBON_COMPONENTS_NEWCOMPONENT_NEWTLINE 33256
#define ID_RIBBON_COMPONENTS_NEWCOMPONENT_NEWCABLE 33257
#define ID_RIBBON_COMPONENTS_NEWCOMPONENT_WIREMODE 33258
#define ID_RIBBON_FORMAT_GRAPHICFILTERS_START 33300
#define ID_RIBBON_FORMAT_GRAPHICFILTERS_ARCS 33300
#define ID_RIBBON_FORMAT_GRAPHICFILTERS_LINES 33301
#define ID_RIBBON_FORMAT_GRAPHICFILTERS_RECTANGLES 33302
#define ID_RIBBON_FORMAT_GRAPHICFILTERS_LABEL 33303
#define ID_RIBBON_FORMAT_GRAPHICFILTERS_CONNECTIONS 33304
#define ID_RIBBON_FORMAT_GRAPHICFILTERS_ELIPSES 33305
#define ID_RIBBON_FORMAT_GRAPHICFILTERS_IMAGES 33306
#define ID_RIBBON_FORMAT_GRAPHICFILTERS_END 33309
#define ID_RIBBON_FORMAT_LAYERS_SET     33310
#define ID_RIBBON_FORMAT_LAYERS_HIDEALL 33311
#define ID_RIBBON_FORMAT_LAYERS_SHOWALL 33312
#define ID_RIBBON_FORMAT_SHAPES_START   33315
#define ID_RIBBON_FORMAT_SHAPES_LINE    33315
#define ID_RIBBON_FORMAT_SHAPES_RECTANGLE 33316
#define ID_RIBBON_FORMAT_SHAPES_ELLIPSE 33317
#define ID_RIBBON_FORMAT_SHAPES_ARC90   33318
#define ID_RIBBON_FORMAT_SHAPES_ARC180  33319
#define ID_RIBBON_FORMAT_SHAPES_CONNECTION 33320
#define ID_RIBBON_FORMAT_SHAPES_LABEL   33321
#define ID_RIBBON_FORMAT_SHAPES_IMG     33322
#define ID_RIBBON_FORMAT_SHAPES_END     33324
#define ID_RIBBON_FORMAT_EDITING_FINDSYMBOL 33380
#define ID_RIBBON_FORMAT_EDITING_REPLACE 33381
#define ID_RIBBON_FORMAT_EDITING_SEGMENTMANAGER 33382
#define ID_RIBBON_FORMAT_EDITING_SELECTSEGMENT 33383
#define ID_RIBBON_FORMAT_COMPINENTS_ORIENTATION_START 33385
#define ID_RIBBON_FORMAT_COMPONENTS_ORIENTATION_ROTATE_CLOCKWISE 33385
#define ID_RIBBON_FORMAT_COMPONENTS_ORIENTATION_ROTATE_COUNTERCLOCKWISE 33386
#define ID_RIBBON_FORMAT_COMPONENTS_ORIENTATION_FLIP_HORZ 33387
#define ID_RIBBON_FORMAT_COMPONENTS_ORIENTATION_FLIP_VERT 33388
#define ID_RIBBON_FORMAT_COMPINENTS_ORIENTATION_END 33390
#define ID_RIBBON_FORMAT_IMPORT_RESOURCE 33391
#define ID_RIBBON_BETA_SYSTEM_QUERY     33400
#define ID_RIBBON_BETA_NETWORK_EQUIVALENT_GENERATE 33401
#define ID_RIBBON_BETA_NETWORK_EQUIVALENT_IMPORT 33402
#define ID_RIBBON_BETA_NETWORK_EQUIVALENT 33403
#define ID_RIBBON_BETA_SYSTEM_QUERY_SERVER 33404
#define ID_RIBBON_BETA_SYSTEM_QUERY_CLIENT 33405
#define ID_RIBBON_BETA_LIVEWIRE         33407
#define ID_RIBBON_BETA_MEDIC            33408
#define ID_RIBBON_EDIT_CONDSTATE_CONDITIONAL 33425
#define ID_RIBBON_EDIT_CONNECTION_CONNECTION 33426
#define ID_RIBBON_EDIT_LINE_COLOUR      33430
#define ID_RIBBON_EDIT_LINE_WEIGHT      33431
#define ID_RIBBON_EDIT_LINE_WEIGHT_START 33431
#define ID_RIBBON_EDIT_LINE_WEIGHT_02   33432
#define ID_RIBBON_EDIT_LINE_WEIGHT_04   33433
#define ID_RIBBON_EDIT_LINE_WEIGHT_06   33434
#define ID_RIBBON_EDIT_LINE_WEIGHT_08   33435
#define ID_RIBBON_EDIT_LINE_WEIGHT_10   33436
#define ID_RIBBON_EDIT_LINE_WEIGHT_12   33437
#define ID_RIBBON_EDIT_LINE_WEIGHT_14   33438
#define ID_RIBBON_EDIT_LINE_WEIGHT_END  33440
#define ID_RIBBON_EDIT_LINE_STYLE       33441
#define ID_RIBBON_EDIT_LINE_STYLE_START 33441
#define ID_RIBBON_EDIT_LINE_STYLE_SOLID 33442
#define ID_RIBBON_EDIT_LINE_STYLE_DASH  33443
#define ID_RIBBON_EDIT_LINE_STYLE_DOT   33444
#define ID_RIBBON_EDIT_LINE_STYLE_DASHDOT 33445
#define ID_RIBBON_EDIT_LINE_STYLE_END   33450
#define ID_RIBBON_EDIT_RECT_TRANSPARENCY 33451
#define ID_RIBBON_EDIT_RECT_TRANSPARENCT_START 33451
#define ID_RIBBON_EDIT_RECT_TRANSPARENCT_TRANS 33452
#define ID_RIBBON_EDIT_RECT_TRANSPARENCY_PATTERN 33453
#define ID_RIBBON_EDIT_RECT_TRANSPARENCY_SOLID 33454
#define ID_RIBBON_EDIT_RECT_TRANSPARENCY_END 33455
#define ID_RIBBON_EDIT_RECT_TRANSPARENCY_PATTERN_START 33456
#define ID_RIBBON_EDIT_RECT_TRANSPARENCY_PATTERN_HORZ 33456
#define ID_RIBBON_EDIT_RECT_TRANSPARENCY_PATTERN_VERT 33457
#define ID_RIBBON_EDIT_RECT_TRANSPARENCY_PATTERN_FORWARDDIAG 33458
#define ID_RIBBON_EDIT_RECT_TRANSPARENCY_PATTERN_BACKWARDDIAG 33459
#define ID_RIBBON_EDIT_RECT_TRANSPARENCY_PATTERN_HORZCROSS 33460
#define ID_RIBBON_EDIT_RECT_TRANSPARENCY_PATTERN_DIAGCROSS 33461
#define ID_RIBBON_EDIT_RECT_TRANSPARENCY_PATTERN_END 33465
#define ID_RIBBON_EDIT_RECT_FORGROUND   33467
#define ID_RIBBON_EDIT_RECT_BACKROUND   33468
#define ID_RIBBON_EDIT_ARC_START        33470
#define ID_RIBBON_EDIT_ARC_SWEEP        33471
#define ID_RIBBON_EDIT_NODE_SYMBOL      33475
#define ID_RIBBON_EDIT_NODE_DIMENSION   33476
#define ID_RIBBON_EDIT_NODE_INTERNAL    33477
#define ID_RIBBON_EDIT_NODE_CONTYPE     33478
#define ID_RIBBON_EDIT_NODE_NODETYPE    33479
#define ID_RIBBON_EDIT_NODE_DATATYPE    33480
#define ID_RIBBON_EDIT_LABEL_TEXT       33485
#define ID_RIBBON_EDIT_LABEL_SIZE       33486
#define ID_RIBBON_EDIT_LABEL_ALIGN      33487
#define ID_RIBBON_MAP_DRAWING_DRAWTLINE 33500
#define ID_RIBBON_MAP_DRAWING_ADDSTATION 33501
#define ID_RIBBON_MAP_DRAWING_ADDTOWER  33502
#define ID_RIBBON_MAP_SEGMENTS_TLINESEGMENTFILL 33505
#define ID_RIBBON_MAP_SEGEMNTS_DISTANCE 33506
#define ID_RIBBON_MAP_FILE_SAVE         33510
#define ID_RIBBON_MAP_FILE_LOAD         33511
#define ID_RIBBON_MAP_FILE_IMPORT       33512
#define ID_RIBBON_MAP_FILE_EXPORT       33513
#define ID_RIBBON_MAP_FIND_GOTO         33515
#define ID_RIBBON_MAP_FIND_GOTOTEXT     33516
#define ID_RIBBON_MAP_DELETE_DELETE     33518
#define ID_RIBBON_POWERFLOW_COMPONENTS_START 33550
#define ID_RIBBON_POWERFLOW_COMPONENTS_BUS 33550
#define ID_RIBBON_POWERFLOW_COMPONENTS_ACLINE 33551
#define ID_RIBBON_POWERFLOW_COMPONENTS_HVDCLINE 33552
#define ID_RIBBON_POWERFLOW_COMPONENTS_2WINDINGT 33553
#define ID_RIBBON_POWERFLOW_COMPONENTS_3WINDINGT 33554
#define ID_RIBBON_POWERFLOW_COMPONENTS_FACTS 33555
#define ID_RIBBON_POWERFLOW_COMPONENTS_GENERATOR 33556
#define ID_RIBBON_POWERFLOW_COMPONENTS_LOAD 33557
#define ID_RIBBON_POWERFLOW_COMPONENTS_SHUNT 33558
#define ID_RIBBON_POWERFLOW_COMPONENTS_STUB 33559
#define ID_RIBBON_POWERFLOW_COMPONENTS_END 33560
#define ID_RIBBON_POWERFLOW_SETTINGS_START 33561
#define ID_RIBBON_POWERFLOW_SETTINGS_FLATSTART 33561
#define ID_RIBBON_POWERFLOW_SETTINGS_ITER 33564
#define ID_RIBBON_POWERFLOW_SETTINGS_PRES 33567
#define ID_RIBBON_POWERFLOW_SETTINGS_ZEROIMPTHRES 33570
#define ID_RIBBON_POWERFLOW_SETTINGS_SOLUTION 33571
#define ID_RIBBON_POWERFLOW_SETTINGS_END 33575
#define ID_RIBBON_POWERFLOW_SOLVE_BEGIN 33576
#define ID_RIBBON_POWERFLOW_SOLVE_SOLVE 33576
#define ID_RIBBON_POWERFLOW_SOLVE_END   33580
#define ID_RIBBON_POWERFLOW_VIEW_VIEW   33586
#define ID_RIBBON_POWERFLOW_DRAWING_LOCKBRANCHES 33590
#define ID_RIBBON_POWERFLOW_SYSDATA_OPEN 33591
#define ID_RIBBON_POWERFLOW_SYSDATA_EXPORT_RAW 33592
#define ID_RIBBON_POWERFLOW_SYSDATA_EXPORT_XML 33593
#define ID_RIBBON_HOME_RUN_RUNSIM       33600
#define ID_RIBBON_HOME_RUN_RUNALLSIMS   33601
#define IDM_ADD_TO_SIMULATION           33623
#define ID_RIBBON_UPDATE_SIM_RUN        33632
#define ID_RIBBON_RUN_SIMULATION        33633
#define DYNAMIC_SIM_ID_START            33650
#define DYNAMIC_SIM_ID_END              33800
#define ID_RIBBON_TOOLS_COMPARATOR_COMPARE 33850
#define ID_RIBBON_TOOLS_COMPARATOR_PRIMARY 33851
#define ID_RIBBON_TOOLS_COMPARATOR_SECONDARY 33852
#define ID_RIBBON_TOOLS_COMPARATOR_PRIMARYSOURCEDESC 33853
#define ID_RIBBON_TOOLS_COMPARATOR_SECONDARYSOURCEDESC 33854
#define ID_RIBBON_TOOLS_COMPARATOR_REFRESHSOURCES 33855
#define ID_RIBBON_TOOLS_COMPARATOR_SHOWHIDE 33856
#define ID_RIBBON_DOV_DOV_VIEWSINGLECURVE 33875
#define ID_RIBBON_DOV_DOV_VIEWSALLCURVES 33876
#define ID_RIBBON_DOV_DOV_XAXISSETTINGS 33879
#define ID_RIBBON_DOV_DOV_SELECTOR      33880
#define ID_RIBBON_MASTERLIBRARY_POPULATE_REFRESHTAB 33975
#define ID_RIBBON_OTHER_HELP            33980
#define ID_RIBBON_OTHER_MIN             33981
#define ID_RIBBON_OTHER_LOGIN           33982
#define ID_RIBBON_CONTEXT_SCHEMATIC     33990
#define ID_RIBBON_CONTEXT_GRAPHIC       33991
#define ID_RIBBON_CONTEXT_STATION       33992
#define ID_RIBBON_CONTEXT_MAPVIEW       33994
#define ID_RIBBON_CONTEXT_COMPARATOR    33995
#define ID_RIBBON_CONTEXT_LCP           33996
#define ID_RIBBON_CONTEXT_TLINES        33997
#define ID_RIBBON_CONTEXT_CABLE         33998
#define ID_RIBBON_MAIN                  34000
#define ID_RIBBON_MAIN_NEW_PROJECT      34010
#define ID_RIBBON_MAIN_NEW_LIBRARY      34011
#define ID_RIBBON_MAIN_NEW_WORKSPACE    34012
#define ID_RIBBON_MAIN_OPEN             34019
#define ID_RIBBON_MAIN_OPEN_PROJECT     34020
#define ID_RIBBON_MAIN_OPEN_IMPORT      34021
#define ID_RIBBON_MAIN_OPEN_WORKSPACE   34022
#define ID_RIBBON_MAIN_OPEN_EXAMPLES    34023
#define ID_RIBBON_MAIN_OPEN_SIMULATIONS 34024
#define ID_RIBBON_MAIN_SAVE             34029
#define ID_RIBBON_MAIN_SAVE_PROJECT     34030
#define ID_RIBBON_MAIN_SAVE_PROJECT_AS  34031
#define ID_RIBBON_MAIN_SAVE_WORKSPACE   34032
#define ID_RIBBON_MAIN_SAVE_WORKSPACE_AS 34033
#define ID_RIBBON_MAIN_UNLOAD_PROJECT   34050
#define ID_RIBBON_MAIN_UNLOAD_ALL       34051
#define ID_RIBBON_MAIN_PRINT            34060
#define ID_RIBBON_MAIN_PRINT_PAGE       34061
#define ID_RIBBON_MAIN_PRINT_PREVIEW    34062
#define ID_RIBBON_MAIN_PRINT_ALL        34063
#define ID_RIBBON_MAIN_PRINT_ALLPREVIEW 34064
#define ID_RIBBON_MAIN_PRINT_SETUP      34065
#define ID_RIBBON_MAIN_HELP_TABLEOFCONTENTS 34070
#define ID_RIBBON_MAIN_HELP_INDEX       34071
#define ID_RIBBON_MAIN_HELP_KEYBOARD    34072
#define ID_RIBBON_MAIN_HELP_UNITSYSTEM  34073
#define ID_RIBBON_MAIN_HELP_COMPONENTWIZARD 34074
#define ID_RIBBON_MAIN_HELP_ONLINECONTROLS 34075
#define ID_RIBBON_MAIN_HELP_TLINEANDCABLES 34076
#define ID_RIBBON_MAIN_HELP_CONTACT     34077
#define ID_RIBBON_MAIN_HELP_ONLINEPLOTTING 34078
#define ID_RIBBON_MAIN_HELP_SUPPORT     34079
#define ID_RIBBON_MAIN_HELP_WHATSNEW    34080
#define ID_RIBBON_MAIN_HELP_COPYRIGHT   34081
#define ID_RIBBON_MAIN_HELP_ABOUT       34082
#define ID_RIBBON_MAIN_HELP_ONLINE      34083
#define ID_RIBBON_MAIN_SETTINGS         34090
#define ID_RIBBON_MAIN_OPTIONS          34091
#define ID_RIBBON_MAIN_EXIT             34092
#define ID_RIBBON_MAIN_SUBSTITUTIONS    34500
#define ID_RIBBON_MAIN_SUBSTITUTIONS_SAVE_AS 34501
#define ID_RIBBON_MAIN_SUBSTITUTIONS_LOAD 34502
#define ID_RIBBON_MAIN_SUBSTITUTIONS_IMPORT 34503
#define ID_RIBBON_MAIN_SUBSTITUTIONS_EXPORT 34504
#define ID_RIBBON_TLINE_COMPONENTS_BEGIN 34700
#define ID_RIBBON_TLINE_COMPONENTS_CROSSSECTION_BEGIN 34700
#define ID_RIBBON_TLINE_COMPONENTS_1COND 34700
#define ID_RIBBON_TLINE_COMPONENTS_2CONDFLAT 34701
#define ID_RIBBON_TLINE_COMPONENTS_3CONDFLAT 34702
#define ID_RIBBON_TLINE_COMPONENTS_6CONDCONCENTRIC 34703
#define ID_RIBBON_TLINE_COMPONENTS_6CONDOFFSET 34704
#define ID_RIBBON_TLINE_COMPONENTS_3CONDDELTA 34705
#define ID_RIBBON_TLINE_COMPONENTS_6CONDDELTA 34706
#define ID_RIBBON_TLINE_COMPONENTS_6CONDFLAT 34707
#define ID_RIBBON_TLINE_COMPONENTS_6CONDVERT 34708
#define ID_RIBBON_TLINE_COMPONENTS_MANUALDATA 34709
#define ID_RIBBON_TLINE_COMPONENTS_12CONDVERT 34710
#define ID_RIBBON_TLINE_COMPONENTS_1CONDBUSBAR 34711
#define ID_RIBBON_TLINE_COMPONENTS_3CONDHORZBUSBAR 34712
#define ID_RIBBON_TLINE_COMPONENTS_3CONDVERTBUSBAR 34713
#define ID_RIBBON_TLINE_COMPONENTS_MANUALXYPOS 34714
#define ID_RIBBON_TLINE_COMPONENTS_3CONDCONCENTRIC 34715
#define ID_RIBBON_TLINE_COMPONENTS_3CONDOFFSET 34716
#define ID_RIBBON_TLINE_COMPONENTS_3CONDVERT 34717
#define ID_RIBBON_TLINE_COMPONENTS_6CONDUCTORVERT 34718
#define ID_RIBBON_TLINE_COMPONENTS_CROSSSECTION_END 34730
#define ID_RIBBON_TLINE_COMPONENTS_MODELS_BEGIN 34731
#define ID_RIBBON_TLINE_COMPONENTS_FREQDEPMODE 34731
#define ID_RIBBON_TLINE_COMPONENTS_BERGMODEL 34732
#define ID_RIBBON_TLINE_COMPONENTS_FREQDEPPHASE 34733
#define ID_RIBBON_TLINE_COMPONENTS_MODELS_END 34739
#define ID_RIBBON_TLINE_COMPONENTS_GROUNDOPTIONS 34740
#define ID_RIBBON_TLINE_COMPONENTS_ADDITONALOPTIONS 34741
#define ID_RIBBON_TLINE_COMPONENTS_END  34750
#define ID_RIBBON_CABLE_COMPONENTS_BEGIN 34800
#define ID_RIBBON_CABLE_COMPONENTS_CROSSECTION_BEGIN 34800
#define ID_RIBBON_CABLE_COMPONENTS_COAXTYPE 34800
#define ID_RIBBON_CABLE_COMPONENTS_PIPETYPE 34801
#define ID_RIBBON_CABLE_COMPONENTS_CROSSECTION_END 34830
#define ID_RIBBON_CABLE_COMPONENTS_MODELS_BEGIN 34831
#define ID_RIBBON_CABLE_COMPONENTS_FREQDEPMODE 34831
#define ID_RIBBON_CABLE_COMPONENTS_BERGMODEL 34832
#define ID_RIBBON_CABLE_COMPONENTS_FREQDEPPHASE 34833
#define ID_RIBBON_CABLE_COMPONENTS_MODELS_END 34839
#define ID_RIBBON_CABLE_COMPONENTS_GROUNDOPTIONS 34840
#define ID_RIBBON_CABLE_COMPONENTS_ADDITONALOPTIONS 34841
#define ID_RIBBON_CABLE_COMPONENTS_END  34850
#define ID_RIBBON_TLINECABLES_TOOLS_SOLVECONSTANTS 34860
#define ID_RIBBON_TLINECABLE_TOOLS_LCP  34861
#define ID_NET_HELP                     34862
#define ID_NET_COPYTOCLIP_FROM_TABLE    34863
#define DYNAMIC_ID_START                36000
#define DYNAMIC_ID_END                  57300
#define DYNAMIC_LAYER_ID_START          57410
#define DYNAMIC_LAYER_ID_END            57442
#define IDM_SIMULATION_SETTINGS         57600
#define IDM_SIMULATION_REMOVE           57601
#define IDM_INCLUDE_ALL_PROJECTS        57603
#define IDM_SIMULATION_RUN              57604
#define IDM_SIMULATION_REMOVE_ALL       57605
#define IDM_TASK_REMOVE                 57606
#define IDR_SIMULATION_SETTINGS_FORM    57607
#define IDM_SIMULATION_ADD              57608
#define IDM_TASK_STOP                   57609
#define IDZ_CMP_CUT                     0xE170
#define IDZ_CMP_COPY                    0xE171
#define IDZ_CMP_PASTE                   0xE172
#define IDZ_CMP_PREV                    0xE173
#define IDZ_CMP_NEXT                    0xE174
#define IDZ_CMP_FIRST                   0xE176
#define IDZ_CMP_LAST                    0xE177
#define IDZ_CMP_PROPS                   0xE178
#define IDZ_CMP_EXPORT                  0xE179
#define IDM_VIEW_ZOOM25                 0xE180
#define IDM_VIEW_ZOOM33                 0xE181
#define IDM_VIEW_ZOOM50                 0xE182
#define IDM_VIEW_ZOOM75                 0xE183
#define IDM_VIEW_ZOOM100                0xE184
#define IDM_VIEW_ZOOM125                0xE185
#define IDM_VIEW_ZOOM150                0xE186
#define IDM_VIEW_ZOOM200                0xE187
#define IDM_VIEW_ZOOM300                0xE188
#define IDM_VIEW_ZOOM400                0xE189
#define IDR_VIEW_ZOOMIN                 0xE190
#define IDR_VIEW_ZOOMOUT                0xE191
#define IDZ_CMP_HELP                    0xE192
#define IDZ_POINT_TO_CHANNEL            0xE193
#define ID_COPYTOCLIP_FROM_TABLE        65501
#define ID_NAVIGATE_FROM_TABLE_BY_ID    65502
#define ID_CLEARALLMESSAGE_FROM_TABLE   65504
#define ID_EXPORT_FROM_TABLE            65505
#define ID_RELOAD_FROM_TABLE            65506
#define ID_NAVIGATE_FROM_COMPARATOR_TABLE 65507
#define ID_COMPONENTMANAGER_USE_SIGNAL_NAME 65508
#define IDC_PAPER_SIZE_BA3              65535
#define IDC_PAPER_SIZE_CA2              65535
#define IDC_PAPER_SIZE_DA1              65535
#define IDC_ETYPE_OUTPUT                65535
#define IDC_ETYPE_ELEC                  65535
#define IDM_CHANNEL_PROPS               65535
#define IDC_SHOW_SIGNALS                65535
#define IDC_TRANSPARENT                 65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        691
#define _APS_NEXT_COMMAND_VALUE         6619
#define _APS_NEXT_CONTROL_VALUE         1318
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
